### ISSUE TITLE
FTB Omnia 1.0.0 crashes at startup

### ISSUE THREAD

**Issue by fuzzyray** [FTBTeam/FTB-Omnia#1]
* **Modpack Version**: FTB Omnia 1.0.0

* **Issue**: The modpack crashes at startup, I get the initial FML early loading screen, it goes away and the game crashes.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/188ee88e

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Unclear from crash report

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Hi Fuzzy,
This is an issue with Forge/Minecraft, the forge people are aware of the issue.

**Comment by Sunekaer** [comment]
Should be fixed with newer forge versions
