### ISSUE TITLE
Minetogether Crashing Game

### ISSUE THREAD

**Issue by k-willow** [FTBTeam/FTB-Omnia#10]
* **Modpack Version**: 1.0.1

* **Issue**: Whenever I attempt to sleep or open chat, the game crashes. The error code I receive seems to say that the Minetogether GUI is not properly opening. Only started recently.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8f5c83f3

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Minetogether.

* **Known Fix**: I temporarily removed Minetogether and it seems to not crash anymore.

**Comment by Sunekaer** [comment]
#5
