### ISSUE TITLE
Crafting RFTools Shield Projector Tier 2 make server crash

### ISSUE THREAD

**Issue by Mysteriosis** [FTBTeam/FTB-Omnia#100]
* **Modpack Version**: 1.4

* **Issue**: Trying to craft the item "Shield Projector Tier 2" from RFTools, When the last component put on crafting table is the "Shield Projector Tier 1", the whole server crashes.

* **Link to Log or Crash File Paste**: Actually no access to the server

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: RFTools

* **Known Fix**: No, just build the craft in another order

**Comment by Naxanria** [comment]
Can not do much without the crashlogs. Is there a way to get them?

**Comment by Mysteriosis** [comment]
I tried to get it again but I cannot repeat this error anymore... I think It's ok then ?

**Comment by Naxanria** [comment]
IN that case I am closing the issue. If it arises again, please make a new issue with the logs included :)

**Comment by Mysteriosis** [comment]
FYI I still have managed to find the log.
Hope it could help you: https://paste.feed-the-beast.com/view/f0c9cec3
