### ISSUE TITLE
Log spam only mekanism

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#103]
* **Modpack Version**: 
1.4.0
* **Issue**: 

Mekansim is spamming console saying that a transmitter is already registered at this location

* **Link to Log or Crash File Paste**: 

https://paste.feed-the-beast.com/view/7716f3df

* **Is it Repeatable?**: 

Yes

* **Mod/s Affected**: 

Mekanism

* **Known Fix**: 

Removing and placing does not fix, removing is the only way.

**Comment by Sunekaer** [comment]
Fixed in newer version
