### ISSUE TITLE
1.4.0 Crimson Meal issue seem to be back(?) / not working with Harvest (config option ignored)

### ISSUE THREAD

**Issue by Sascha-Peter** [FTBTeam/FTB-Omnia#104]
* **Modpack Version**: 1.4.0

* **Issue**: Harvest seem to ignore netherwart = false config file leading to using natures aura crimson meal on nether warts to not work. Tried to change the harvest config file to change the value from false to true in case of something having changed, and tried to play with the blacklist which didn't work as I couldn't find out what values are accepted.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Harvest 1.0.1, Naturesaura-27.0

* **Known Fix**: From the previous bug report, it read like that the option "netherwart = false" is the solution to this in the config file of harvest, but that option doesn't seem to be used / acknowledged. I've changed the value of netherwart to true as well in case it changed, tried the blacklist (which I couldn't figure out the correct parsing of or how to type it that it takes the value so removed again as it didn't let the server boot) and tried to work around that with no success.

**Comment by Naxanria** [comment]
This is fixed in 1.0.2 version of the mod

**Comment by Sascha-Peter** [comment]
Awesome, thanks! Appreciate that this will be hard to say probably but do we have a rough view on when the next modpack update might release with this fix included?

**Comment by Naxanria** [comment]
No idea yet.

**Comment by Sascha-Peter** [comment]
Apologies for not coming back earlier - since it also changed the forge version I assume an intermediate/manual fiddling with the mods will not be possible without potential side effects for us. 
We'll wait for the official release, thanks again!
