### ISSUE TITLE
I can't tell if this is a bug or not but is has to do with JEI

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#105]
I got word that one of my players had to throw out an item because he was able to cheat it in. He is not opped at all but it gave him 1 turtle egg. This is what he said to me,

Mr Pikachu Today at 12:08 AM
So How did you do it?

Alexdapheonix Today at 12:09 AM
i ctrl clicked jei config simbol
[12:09 AM]
symbol

I went onto the server config files and found nothing JEI related same for the configs in the world folder, I then went to the client side and it had a JEI folder but nothing in it. Is there a way to cancel this action from going through or something of that sort?

**Comment by Sunekaer** [comment]
I tested in SP and it says "you do not have permission to use JEU's Cheat Mode. Permission is given to players who can /give items or are in Creative Mode".
Please check the player don't have that permission and if they don't please report it to JEI at https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
