### ISSUE TITLE
[Bug] Client and Server recipes.js are different.

### ISSUE THREAD

**Issue by Lassendc** [FTBTeam/FTB-Omnia#107]
Client and Server \kubejs\data\modpack\kubejs\recipes.js are different.
The server file has an extra recipe for animalcrops:pollen witch the client file do not, **followed by an syntax error at line 81** witch most likely is also why you can not crush soul sand into vile dust on servers.

**Comment by AngelicBeatz** [comment]
duplicate https://github.com/FTBTeam/FTB-Omnia/issues/14
