### ISSUE TITLE
Mod request for server side utilities but required on both client and servers

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#108]
Hi I was wondering if you guys would think about adding this to the pack. It would help servers greatly till plugins or something of that sort ever make it to 1.15.2

https://www.curseforge.com/minecraft/mc-mods/maessentials

**Comment by Sunekaer** [comment]
What is it from this mod you need that we don't already have in the FTB mods?

**Comment by AngelicBeatz** [comment]
I will say the FTB rank system and the backup system are great but the / cmds in the above link would greatly add more control to server operators and owners, while also giving players more leash in what they can do. The FTB mods as they are the TPS one is even nice but does not do a clear of lag (would be awesome to have tho) unless in the 1.5.0 you guys are planning to add many more commands. The reason why I am asking 1st is I do not want/cause any issues by uploading a version of Omnia on a different platform with just this added. I feel that would be stealing your work and I do not want to do that as this pack has true greatness for the future of the modding community.

**Comment by Sunekaer** [comment]
Forge has a TPS command?
Time/Weather/Setpawn commands can be done with vanilla commands.
Spawn, home, warp, tpa and more will be added back to the FTB mods eventually but we have a lot of mods to update and maintain.
Clear lag system you can use KubeJS which is in the pack and add a script server-side like https://gist.github.com/LatvianModder/9f5f8cb4121fda4141dbd2cfd5b3d5c9#file-clearlag-js

**Comment by AngelicBeatz** [comment]
O sorry I said ftb has a tps but it’s forge that has it

/forge tps (dim name)
/forge tps

I will try out the scripts was not aware of that stuff.

**Comment by AngelicBeatz** [comment]
Wow just looking at those scripts, wow the things I can do now :o thanks @Sunekaer i might even be able to use my ras pi again like in 1.7.10 :D

**Comment by Sunekaer** [comment]
for question regarding kubejs you can ask on https://discord.gg/bPFfH6P
