### ISSUE TITLE
Game Stuttering.

### ISSUE THREAD

**Issue by DimmerSteam** [FTBTeam/FTB-Omnia#109]
* **Modpack Version**: v1.4.0

* **Issue**: Around every 10~ seconds the game will freeze/stutter for a few seconds (I don't have this problem with any other mod packs.)

* **Link to Log or Crash File Paste**: None.

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: None.

* **Known Fix**: None.

**Comment by Sunekaer** [comment]
Sounds like your hitting the garbage collector, try assigning more ram to the pack
