### ISSUE TITLE
Better description needed

### ISSUE THREAD

**Issue by elektronemulo** [FTBTeam/FTB-Omnia#11]
* **Modpack Version**: 
1.0.0 to 1.0.1

* **Issue**: 
Description file is incomplete. Omnia may be a new pack but it really needs a better description of what's in the pack. Thanks.

* **Link to Log or Crash File Paste**: 
Not applicable

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
Pack level

* **Known Fix**:

**Comment by Sunekaer** [comment]
Added
Omnia is not a themed pack, Omnia brings together some of the best mods released on the latest version of Minecraft.
Omnia focuses mainly on mods that revolve around tech and exploration
