### ISSUE TITLE
Can't get Vile Dust due to recipe conflict, Soul Glass recipe takes priority

### ISSUE THREAD

**Issue by SmolFloofyRedhead** [FTBTeam/FTB-Omnia#111]
* **Modpack Version**: 1.5.0

* **Issue**: Both Vile Dust and Soul Glass have the same recipe, and the Soul Glass one is always the one used when I try to smelt soul sand. I'd made 3 shards before trying to make a soul cage and finding out that it's unobtainable.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes. Every time I try to make the dust it makes soul glass instead.

* **Mod/s Affected**: Soul Shards Respawn, Dark Utils

* **Known Fix**: Changing one recipe, but the pack doesn't seem to have any recipe changing mod.

**Comment by Sunekaer** [comment]
Did you update or fresh install the pack?

**Comment by SmolFloofyRedhead** [comment]
Yep. Updated it yesterday. Though, my connection crapped out and the update didn't finish properly despite me hitting Retry once the connection was fine again, so I backdated and re-updated the pack and that worked. Is there some kinda recipe script the FTB app failed to grab? I seems to fuck up updates and installs, cause the first time I tried to install Sky Odyssey it installed with only Forge! It didn't grab a single mod and I had to delete the entire instance folder.

**Comment by AngelicBeatz** [comment]
it still does not seem to work on the server, yes I checked for line 81, I tried it in a crusher but that did not work and in a furnace it gave me the glass. @Sunekaer 

edit: this is in a fresh server copy of 1.5.0 reset world and all to fix MANY issues that also fixed console spam and such.

**Comment by Sunekaer** [comment]
@AngelicBeatz are you replying on the wrong issue??

@SmolFloofyRedhead Could you paste the content of kubejs\data\modpack\kubejs\recipes.js on to https://paste.feed-the-beast.com/ and link it here?

**Comment by SpookyCleric** [comment]
I have re-created this, I think it's just a recipe clash rather than a bug.

**Comment by AngelicBeatz** [comment]
Is it still line 81? I’ll check later

Christopher Sanchez
________________________________

**Comment by AngelicBeatz** [comment]
O no this is the correct place I meant to reply but I got worse news, fresh install of 1.5.0 and it seems there’s compatibility issues one of my players found. Is this intentional or an error.

![27DFECED-D779-4393-8521-9D6FBED4898F](https://user-images.githubusercontent.com/24941674/84582786-23882700-adb6-11ea-9de7-bbd6c7374269.png)

**Comment by Sunekaer** [comment]
AngelicBeatz please make an new issue and keep this one for the original issue

**Comment by AngelicBeatz** [comment]
Will do didn’t know if I should have, I will edit my replies above. Sorry about that.

Christopher Sanchez
________________________________
