### ISSUE TITLE
Map Death markers won't delete. 

### ISSUE THREAD

**Issue by SpookyCleric** [FTBTeam/FTB-Omnia#112]
* **Modpack Version**: 1.5.0

* **Issue**: Death markers on FTB map reappear after deletion once you close the map. Initially they remained deleted, however I can see my own and another players (who plays via LAN) and was unable to remove them, seemingly without cause.  

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes, can't get it to stop. I've tried reloading, reinstalling, etc. 

* **Mod/s Affected**: I think the map is part of ftb-chunks-1.1.0.12

* **Known Fix**: No fix as of yet.

**Comment by LatvianModder** [comment]
This is a bug, where it sends you your ally death markers. This will be fixed soon. for now, ask whoever has added you as ally to clear up their map :p

**Comment by Sunekaer** [comment]
feature been disabled.
