### ISSUE TITLE
Going up to a clean install of 1.5.0 cleaned up many issues but a few things got bugged possibly not sure

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#114]
* **Modpack Version**: 
1.5.0
* **Issue**: 
It would seem that some recipes do not work correctly.
https://imgur.com/a/iyaDMtf
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
On my server yes
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by AngelicBeatz** [comment]
I am also back at work (truck driver long hours) so I will be trying my best to be on top of this. I don’t know if it’s an error on my side or not. The groups that are on my server can help you out also. They are a bunch of server crashers but they do love to find bugs xD

**Comment by Sunekaer** [comment]
Something is wrong with the recipe script on your server, works fine in my dev instance
Could you paste the content of kubejs\data\modpack\kubejs\recipes.js on to https://paste.feed-the-beast.com/ and link it here?

**Comment by AngelicBeatz** [comment]
This afternoon I might have some time

Christopher Sanchez
________________________________

**Comment by AngelicBeatz** [comment]
Ok this is what I have in that folder. I added clear lag and starting items to the script file. Those are directly from where you sent me to look. 
![5B96337F-5ABF-4A69-9FB5-5279E8313882](https://user-images.githubusercontent.com/24941674/84668882-c3929d00-aee9-11ea-94c5-c5a913281ed7.png)

https://pastebin.com/043eBhfj

**Comment by Sunekaer** [comment]
hmm okay, all the recipes is there and the file seems fine, could you link me the latest.log
