### ISSUE TITLE
Error booting

### ISSUE THREAD

**Issue by JasperRC** [FTBTeam/FTB-Omnia#115]
* **Modpack Version**: 1.5.0

* **Issue**: I'm new to modding so I'm not really sure how to do this stuff so I'm not really sure how to paste the log thing. Anyway, I try to launch the game and it just shows the screen in the image.
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7dc58578
* **Is it Repeatable?**: 

* **Mod/s Affected**: archers paradox and encorcellation
* **Known Fix**: Nope
![FTB Omnia 6_14_2020 8_38_12 PM](https://user-images.githubusercontent.com/66572295/84616186-1d5e7d00-ae80-11ea-98bb-3886c54a3ed3.png)

**Comment by Sunekaer** [comment]
Seems like something is wrong with your installation please reinstall it

**Comment by JasperRC** [comment]
I reinstalled it and it still has that error.

**Comment by JasperRC** [comment]
Is this not happening for anyone else?

**Comment by Sunekaer** [comment]
Hmm okay can you please provide me with you app log 
https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Comment by JasperRC** [comment]
Nevermind I fixed it by dropping the cofhcore mod into the mods folder! That is ok to do right?

**Comment by Sunekaer** [comment]
Sure, but you might be missing other mods

**Comment by vformsp** [comment]
Hello, I have similiar issue, but Im missing 19 mods.
![Screenshot_2](https://user-images.githubusercontent.com/66963836/84681767-4ee94e00-af3d-11ea-92af-1324bbf22e59.png)

Couple days ago I had problem with installing the new ftb app. I dont know if its related but here is the forum link about it ( https://forum.feed-the-beast.com/threads/ftbapp-cant-download.302776/#post-2022971 )

Im currently trying to upload my app log but cant. ( http://prntscr.com/t07wod ) I will keep trying to upload, and post it after if I can menage to upload it.

**Comment by JasperRC** [comment]
How would I know what mods I am missing?

**Comment by JasperRC** [comment]
https://pste.ch/aqatuxajuj
Here are my app logs if you need them

**Comment by Sunekaer** [comment]
Perfect I see there is a there failed to download, we are working on getting the issue resolved

**Comment by JasperRC** [comment]
Oh thanks so it is not an issue on my end?

**Comment by vformsp** [comment]
Or mine I guess?

**Comment by vformsp** [comment]
Update. I deleted the pack and reinstalled it using vpn and I can launch the pack without problem.

**Comment by JasperRC** [comment]
@Sunekaer Has it been fixed yet?

**Comment by Sunekaer** [comment]
Its being worked on

**Comment by JasperRC** [comment]
@Sunekaer Cool no rush just wondering when it's going to be done

**Comment by Sunekaer** [comment]
Should be fixed now, restart the app and download the pack again

**Comment by JasperRC** [comment]
Ok thanks

**Comment by JasperRC** [comment]
Yes it works now
