### ISSUE TITLE
FTB Omnia v1.5.0 Won't download server files

### ISSUE THREAD

**Issue by AsSeenOnTV13** [FTBTeam/FTB-Omnia#116]
* **Modpack Version**: v1.5.0 Server

* **Issue**: I'm having a problem with the server file download, and another thing I've noticed too is that when I updated from version 1.4.0 to 1.5.0, my whole server caused issues. I had to reinstall both client and server to be able to run it properly again, same for some friends that play on the server. Every single mod, when it tries to download, give back an error: WARNING: *******-1.15.2-1.0.3.jar error 404: Not Found! , and WARNING: *********-1.1.0.5.jar size expected does not match remote file size. File size updated. (Replace ******* with the mod name, this being all the mods)

* **Is it Repeatable?**: Happens with latest server installer, all the time

[downloader.txt](https://github.com/FTBTeam/FTB-Omnia/files/4782849/downloader.txt)
[installer.txt](https://github.com/FTBTeam/FTB-Omnia/files/4782850/installer.txt)

**Comment by AsSeenOnTV13** [comment]
Another thing I wanted to add is that the client files all download properly. Only downloading the server installer does no mods download.

**Comment by Sunekaer** [comment]
Thank you for the info, ill have someone look at the issue

**Comment by grothkha** [comment]
Having the same issue when executing the server installer from: https://api.modpacks.ch/public/modpack/6/71/server/linux

[downloader.log](https://github.com/FTBTeam/FTB-Omnia/files/4783124/downloader.log)

This problem did not exist yesterday.

**Comment by Sunekaer** [comment]
Okay fix has been deployed, restart the app and download the server installer again and it should work
