### ISSUE TITLE
Mod - Builder RFTools

### ISSUE THREAD

**Issue by sneckUK** [FTBTeam/FTB-Omnia#118]
* **FTB Omnia 1.15.0 (current) as of writing this
[debug.log](https://github.com/FTBTeam/FTB-Omnia/files/4809509/debug.log)

* **Issue**: Builder RFTools - ShapeCard Clearing Quarry - Place card in qarry then right click on Quarry - game locks up (same with other cards) -  restart required.

If you put the card into the builder and then right click the builder game freezes - close and restart  game to resolve.

Sneak right clicking the card doesn't work ... have some times had it work after a reboot

Builder and cards also seem to be stuck in their dimension and cannot be moved...

* **Is it Repeatable?**: Tested in a creative world and survival (same installation)

* **Mod/s Affected**: N/A  - Not having any other issues with the FTB Omnia currently 

* **Known Fix**: none

**Comment by Sunekaer** [comment]
Sorry for the late reply, life been busy.. 
Please test with version 1.6 or above
