### ISSUE TITLE
Client corruption 1.5.0 

### ISSUE THREAD

**Issue by Chieflego** [FTBTeam/FTB-Omnia#119]
* **Modpack Version**: 1.5.0 omnia

* **Issue**: upon starting the second time after a restart , the pack claims that my drivers are out of date, they are not... and it does not want to load at all past the load screen. forge is likely the issue here and not a mod

* **Link to Log or Crash File Paste**: sadly no log available to me

* **Is it Repeatable?**: this is very repeatable and requires a reinstall of the pack to get back to normal

* **Mod/s Affected**: no known mods are causing the issue other than forge itself

* **Known Fix**: a reinstall of the pack fixes this , you'll have to pull your world data over but that is a small price to pay. a repair button like in twitch that reinstalls the pack while keeping your data would be appreciated

**Comment by Sunekaer** [comment]
Hi could you suggest the repair button on https://github.com/FTBTeam/FTB-App/issues/ and the reason why 
Thanks
