### ISSUE TITLE
Crouching does not prevent falling off blocks

### ISSUE THREAD

**Issue by lachian** [FTBTeam/FTB-Omnia#12]
* **Modpack Version**: 1.1.0

* **Issue**: Crouching does not prevent falling off blocks

* **Link to Log or Crash File Paste**: No Log or crash file

* **Is it Repeatable?**: Yes
1. Place a full block down.
2. Go on top of the full block you just placed.
3. Crouch.
4. While Crouching, walk towards the ledge of the block
5. Crouching _should_ prevent you from falling off the ledge, but you will fall off.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Are you wearing any boots?

**Comment by lachian** [comment]
Not wearing any armor, nor any baubles. Don't have any potion affects either. Can be reproduced as soon as you log in for the first time.

**Comment by Sunekaer** [comment]
Will look in to it

**Comment by Sunekaer** [comment]
https://github.com/ldtteam/Performant/issues/26

**Comment by markgyoni** [comment]
Same for me

**Comment by hvdklauw** [comment]
Fixed by updating performant to [1.15-2.03m](https://www.curseforge.com/minecraft/mc-mods/performant/files/2924601) tested it on Omnia.
