### ISSUE TITLE
Portality - no fluid module recipe

### ISSUE THREAD

**Issue by SpookyCleric** [FTBTeam/FTB-Omnia#120]
* **Modpack Version**: 1.5.0

* **Issue**: There does not seem to be a crafting recipe for fluid module, and JEI does not know one either. 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes, with fresh install, unable to craft. 

* **Mod/s Affected**: Portality 

* **Known Fix**: None I'm aware of

**Comment by Sunekaer** [comment]
Not a bug, they are not enabled by the mod dev
https://github.com/InnovativeOnlineIndustries/Portality/blob/1.15/src/main/resources/data/portality/recipes/fluids_input.jsondisableds
