### ISSUE TITLE
Please consider removing/re-evaluating Rats mod 

### ISSUE THREAD

**Issue by zefie** [FTBTeam/FTB-Omnia#121]
* **Modpack Version**: Omnia v1.5.0

* **Issue**: All issues in this report are a part of the Rats mod and not FTB itself, but asking FTB Team to consider playtesting and then removing (or reconfiguring) the Rats mod due to its bugs:
  * 1. Mobs from the rats modpack do not respect the game spawning rules and will spawn in your house/base/lit caves
  * 2. Pied Piper flute audio is mono, non-directional, and no distance fading, making it utterly useless to find the piper, and really difficult if he spawned in your underground cave system
  * 3. Maybe its because I disabled the Piper Spawning or because I haven't progressed enough in the mod but I have not found a single "Cheese" in the 250+ rats I have killed.

* **Link to Log or Crash File Paste**: Doesn't crash, just diminishes gameplay value

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Rats
* **Known Fix**: My workaround was to disable the spawn of the Pied Piper (raising the rarity works to an extent but if its an always-on server with forced chunk loading, then it spawns a bunch of them while you are offline)

* **Notes**: Please consider removing the mod, or the FTB manually adjust configuration values if the author has not updated the issues with the Pied Piper flute. The cons currently outweigh the pros of having this mod in the pack.

**Comment by SpookyCleric** [comment]
The pied piper does spawn a little too often, however his flute is directional it's just not particularly easy to work out as you said it is a mono track, but the volume does change with distance. 

Cheese is not dropped by rats, you put milk in a cauldron.    

I have not found rats to be spawning oddly, they have their own conditions but they will spawn anywhere with a low light level at any time of day if memory serves.

**Comment by zefie** [comment]
> The pied piper does spawn a little too often, however his flute is directional it's just not particularly easy to work out as you said it is a mono track, but the volume does change with distance.

Yeah, it should change left/right as well :(

> I have not found rats to be spawning oddly, they have their own conditions but they will spawn anywhere with a low light level at any time of day if memory serves.

Maybe it is just the Piper then. He spawned in a well lit base. The rats were fine once I upgraded the base from wood to stone brick and fenced off my crops. Although the Plague Doctor likes to spawn in my well lit 16 chunk area too, but I don't know his parameters, and at least he doesn't spawn in the buildings.

**Comment by GaltoPlays** [comment]
Within an hour of setting up Omnia for my kids (10 & 12) both asked for this mod to be removed. It really is a bit much in it's current iteration.

**Comment by Sunekaer** [comment]
Hi,
The mod wont be removed as it would break works.
As this is an "Early" 1.15.2 pack it is expected to see bugs and those will only be fixed if reported to the mod devs.
