### ISSUE TITLE
Server crashes when entering ratlantis

### ISSUE THREAD

**Issue by MercyPillow** [FTBTeam/FTB-Omnia#122]
* **Modpack Version**: 1.5.0

* **Issue**: Server crashes when entering ratlantis through the portal

* **Link to Log or Crash File Paste**: 
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/26/20 7:05 PM
Description: Exception in server tick loop

java.util.concurrent.CompletionException: net.minecraft.crash.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_221] {}
Caused by: net.minecraft.crash.ReportedException: Exception generating new chunk
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:529) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	... 12 more
Caused by: java.lang.NullPointerException
	at be.nevoka.betterbedrockgenerator.utils.Utils.getDimId(Utils.java:18) ~[?:0.0.6] {re:classloading}
	at be.nevoka.betterbedrockgenerator.BetterBedrockGenerator.shouldModifyBedrock(BetterBedrockGenerator.java:34) ~[?:0.0.6] {re:mixin,re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.handler$zze000$makeBedrock(NoiseChunkGenerator.java:532) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterbedrockgenerator/betterbedrockgenerator.mixins.json:MixinFlattenBedrock,pl:mixin:A}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_222555_a(NoiseChunkGenerator.java) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterbedrockgenerator/betterbedrockgenerator.mixins.json:MixinFlattenBedrock,pl:mixin:A}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_225551_a_(NoiseChunkGenerator.java:213) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterbedrockgenerator/betterbedrockgenerator.mixins.json:MixinFlattenBedrock,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$6(ChunkStatus.java:61) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:518) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1899406608 bytes (1811 MB) / 5362417664 bytes (5114 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 16
	JVM Flags: 4 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx5120M -Xms4096M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.9
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		justenoughbeacons-2.0.jar Just Enough Beacons {justenoughbeacons@2.0 DONE}
		aiotbotania-1.15.2-1.2.2.jar AIOT Botania {aiotbotania@1.2.2 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		pocketstorage-1.15.2-0.7.2.jar Pocket Storage Unit {pocketstorage@1.15.2-0.7.2 DONE}
		JAVD-1.0.0+build.12.minecraft.1.15.2.jar Just Another Void Dim {javd@1.0.0+build.12.minecraft.1.15.2 DONE}
		SilentMechanisms-1.15.2-0.7.2+52.jar Silent's Mechanisms {silents_mechanisms@0.7.2+52 DONE}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		rsgauges-1.15.2-1.2.3.jar Gauges and Switches {rsgauges@1.2.3 DONE}
		findme-1.15.2-1.3.0.jar Find Me {findme@NONE DONE}
		IronJetpacks-1.15.2-3.0.2.jar Iron Jetpacks {ironjetpacks@3.0.2 DONE}
		Controlling-6.1.4.jar Controlling {controlling@6.1.4 DONE}
		ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		citadel-1.1.7.jar Citadel {citadel@1.1.7 DONE}
		Powah-1.15.2-1.1.14.jar Powah {powah@1.1.14 DONE}
		ftb-gui-library-1.0.0.14.jar FTB GUI Library {ftbguilibrary@1.0.0.14 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		potionofbees-1.15.2-1.0.1.jar Potion of Bees {potionofbees@1.15.2-1.0.1 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		buildinggadgets-3.3.5.jar Building Gadgets {buildinggadgets@3.3.5 DONE}
		DarkUtilities-1.15.2-3.0.5.jar Dark Utilities {darkutils@3.0.5 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.7.420.jar Mekanism: Generators {mekanismgenerators@9.10.7 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		XNetGases-1.15.2-1.0.0.jar XNet Gases {xnetgases@1.0.0 DONE}
		TOOLKIT-1.15.2-1.6.4.jar Tool Kit {toolkit@1.15.2-1.6.4 DONE}
		ftb-teams-1.0.0.5.jar FTB Teams {ftbteams@1.0.0.5 DONE}
		absentbydesign-1.15.2-1.0.7.jar Absent By Design Mod {absentbydesign@1.15.2-1.0.7 DONE}
		refinedstorage-1.8.4.jar Refined Storage {refinedstorage@1.8.4 DONE}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 DONE}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 DONE}
		AnimalCrops-1.15.2-0.5.0.jar Animal Crops {animalcrops@1.15.2-0.5.0 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.15.2-2.3.2-e3bf186.jar Industrial Foregoing {industrialforegoing@2.3.2 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		improved-stations-1.1.jar Improved Stations {improved-stations@1.1 DONE}
		entangled-1.2.5-mc1.15.jar Entangled {entangled@1.2.5 DONE}
		BiomesOPlenty-1.15.2-10.0.0.365-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.365 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		Lollipop-1.15.2-1.0.15.jar Lollipop {lollipop@1.0.15 DONE}
		ftb-ranks-1.0.0.3.jar FTB Ranks {ftbranks@1.0.0.3 DONE}
		wtbw_lib-1.15.2-1.0.21.jar WTBW Library {wtbw_lib@1.0.21 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		simplybackpacks-1.15.2-1.4.6.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.6 DONE}
		portality-1.15.2-2.1.2-aaa257f.jar Portality {portality@2.1.2 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-384.jar Botania {botania@r1.15-384 DONE}
		Patchouli-1.15.2-1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		tanknull-1.8a.jar Tank Null {tanknull@1.8a DONE}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		ftb-ultimine-1.0.8.5.jar FTB Ultimine {ftbultimine@1.0.8.5 DONE}
		wirelessredstone-1.15.2-0.1.0.jar Wireless Redstone {wirelessredstone@0.1.0 DONE}
		NaturesAura-28.2.jar Nature's Aura {naturesaura@28.2 DONE}
		MekanismTools-1.15.2-9.10.7.420.jar Mekanism: Tools {mekanismtools@9.10.7 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		cc-tweaked-1.15.2-1.88.1.jar CC: Tweaked {computercraft@1.88.1 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		the_bumblezone-1.15.2-1.3.5.jar The Bumblezone {the_bumblezone@1.15.2-1.3.5 DONE}
		YAMDA-5.0.3.jar YAMDA {yamda@5.0.3 DONE}
		speedyladders-1.15.2-1.jar Speedy Ladders {speedyladders@1.15.2-1 DONE}
		Disenchanting-forge_1.15.2-1.5.0.jar Disenchanting {disenchanting@1.5.0 DONE}
		SimpleDiscordRichPresence-1.15.2-1.2.6.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.6 DONE}
		QuantumStorage-1.15.2-5.1.1.jar QuantumStorage {quantumstorage@NONE DONE}
		Cyclic-1.15.2-0.4.1.jar Cyclic {cyclic@1.15.2-0.4.1 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		jmh_1.15.2-2.2.jar Just Mob Heads {jmh@2.2 DONE}
		Cucumber-1.15.2-3.0.7.jar Cucumber Library {cucumber@3.0.7 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		torchslabmod-1.15.2_v1.6.15.jar Torch Slab Mod {torchslabmod@1.6.15 DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		snad-1.8.7.21a-1.15.2.jar Snad {snad@1.8.7.21a DONE}
		item-filters-2.2.0.14.jar Item Filters {itemfilters@2.2.0.14 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		kubejs-2.6.1.34.jar KubeJS {kubejs@2.6.1.34 DONE}
		longfallboots-1.4.0c.jar Long Fall Boots {longfallboots@1.4.0c DONE}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 DONE}
		tesseract-1.0.5-mc1.15.jar Tesseract {tesseract@1.0.5 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.10.7.420.jar Mekanism {mekanism@9.10.7 DONE}
		polarizingbiomes-1.15.1-v1.0.jar Polarizing Biomes {polarizingbiomes@v1.0 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		LightOverlay-4.6.1.jar Light Overlay Forge {lightoverlay-forge@4.6.1 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		mcmc-1.0.0.3.jar MCMC {mcmc@1.0.0.3 DONE}
		good-nights-sleep-1.15.2-1.0.3.jar Good Night's Sleep {goodnightsleep@1.0.3 DONE}
		additionalbars-1.3.5.jar Additional Bars {additionalbars@1.3.5 DONE}
		SimpleStorageNetwork-1.15.2-0.3.2.jar Simple Storage Network {storagenetwork@1.15.2-0.3.2 DONE}
		DimStorage-1.15.2-3.1.5.jar DimStorage {dimstorage@3.1.5 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		BotanyPots-1.15.2-2.0.17.jar BotanyPots {botanypots@2.0.17 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		RingOfTeleport-1.15.2-1.1.30.jar Ring of Teleport {ring_of_teleport@1.1.30 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.1.1-beta.jar McJtyLib {mcjtylib@1.15-4.1.1-beta DONE}
		rftoolsbase-1.15-1.1.1-beta.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta DONE}
		xnet-1.15-2.1.4-beta.jar XNet {xnet@1.15-2.1.4-beta DONE}
		rftoolsstorage-1.15-1.1.4-beta.jar RFToolsStorage {rftoolsstorage@1.15-1.1.4-beta DONE}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 DONE}
		PackingTape-1.15.2-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		mininggadgets-1.3.5.jar Mining Gadgets {mininggadgets@1.3.5 DONE}
		entitydetectors-1.5.2-1.0.0.jar Entity Detectors {entitydetectors@1.5.2-1.0.0 DONE}
		endercompass-2.0.jar Ender Compass {endercompass@2.0 DONE}
		rftoolspower-1.15-2.1.1-beta.jar RFToolsPower {rftoolspower@1.15-2.1.1-beta DONE}
		ftb-chunks-1.1.0.12.jar FTB Chunks {ftbchunks@1.1.0.12 DONE}
		campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 DONE}
		forge-1.15.2-31.2.9-universal.jar Forge {forge@31.2.9 DONE}
		wtbw_core-1.15.2-1.0.19.jar WTBW Core {wtbw_core@1.0.19 DONE}
		wtbw_tools-1.15.2-1.0.20.jar WTBW Tools {wtbw_tools@1.0.20 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.2.9-server.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b DONE}
		ensorcellation-1.15.2-0.4.1b.jar Ensorcellation {ensorcellation@0.4.1b DONE}
		rftoolsutility-1.15-2.1.3-beta.jar RFToolsUtility {rftoolsutility@1.15-2.1.3-beta DONE}
		theoneprobe-1.15-2.0.3.jar The One Probe {theoneprobe@1.15-2.0.3 DONE}
		distance-1.0.0.1.jar Distance {distance@1.0.0.1 DONE}
		clockout-1.15.2-1.0.0.jar Clockout {clockout@1.15.2-1.0.0 DONE}
		playerplates-1.15-forge-1.0.0.jar Player Plates {playerplates@1.15-forge-1.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.15.2-2.4.1.jar Titanium {titanium@2.4.1 DONE}
		moolands-1.15.2-1.2.1.jar Moolands {moolands@1.2.1 DONE}
		useful_railroads-1.15.2-1.3.2.21.jar Useful Railroads {usefulrailroads@1.3.2.21 DONE}
		SilentLib-1.15.2-4.6.1+49.jar Silent Lib {silentlib@4.6.1+49 DONE}
		wtbw_machines-1.15.2-1.0.24.jar WTBW Machines {wtbw_machines@1.0.24 DONE}
		archers_paradox-1.15.2-0.4.0b.jar Archer's Paradox {archers_paradox@0.4.0b DONE}
		SoulShardsRespawn-forge-1.15.2-1.2.0-15.jar Soul Shards Respawn {soulshards@version DONE}
		Ding-1.15.2-1.1.0.jar Ding {ding@1.1.0 DONE}
		rftoolsbuilder-1.15-2.1.3-beta.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.3-beta DONE}
		MiscAdditions-1.2.3.jar Misc Additions {miscadditions@1.2.3 DONE}
		HunterMod-1.15.2-1.0.3.jar Hunter Mod {huntermod@1.0.3 DONE}
		wtbw_decoration-1.15.2-1.0.16.jar WTBW Decoration {wtbw_decoration@1.0.16 DONE}
		rats-5.3.1-1.15.2.jar Rats {rats@5.3.1 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		ftb-backups-2.1.0.1.jar FTB Utilities: Backups {ftbbackups@2.1.0.1 DONE}
		serverconfigupdater-1.1.jar ServerConfig Updater {serverconfigupdater@1.1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		performant-1.15-2.11m.jar Performant {performant@2.11m DONE}
		DoubleSlabs-1.15-2.4.5.jar Double Slabs {doubleslabs@2.4.5 DONE}
		harvest-1.15.2-1.0.2.jar Harvest {harvest@1.0.2 DONE}
		jph_1.15.2-1.0.jar Just Player Heads {jph@1.0 DONE}
		tubesreloaded-1.15.2-1.3.0c.jar Tubes Reloaded {tubesreloaded@1.15.2-1.3.0c DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		Transport-1.15.2-2.3.0.jar Transport {transport@1.15.2-2.3.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		engineersdecor-1.15.2-1.1.0-b1.jar Engineer's Decor {engineersdecor@1.1.0-b1 DONE}
		minetogether-1.15.2-4.0.0-Beta5.jar MineTogether {minetogether@1.15.2-4.0.0-Beta5 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		waterworks-1.15.2-2.1.2.jar Waterworks {waterworks@1.15.2-2.1.2 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		extremeSoundMuffler-1.2.2_forge-1.15.2.jar Extreme Sound Muffler {extremesoundmuffler@1.2.2_forge-1.15.2 DONE}
		draw_bridge-1.15.2-1.4.3.18.jar Draw Bridge {drawbridge@1.4.3.18 DONE}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 DONE}
	MCMC Modpack Version: ZPoZcgnq-GRk
	Player Count: 2 / 20; [ServerPlayerEntity['pentium_11'/348, l='world', x=750.14, y=73.00, z=-20.10], ServerPlayerEntity['Squibbies'/1168, l='world', x=0.00, y=110.00, z=0.00]]
	Data Packs: vanilla, mod:justenoughbeacons (incompatible), mod:aiotbotania, mod:refinedpipes, mod:pocketstorage (incompatible), mod:javd (incompatible), mod:silents_mechanisms (incompatible), mod:bambooeverything (incompatible), mod:kleeslabs (incompatible), mod:rsgauges, mod:findme (incompatible), mod:ironjetpacks, mod:controlling (incompatible), mod:reauth (incompatible), mod:placebo (incompatible), mod:citadel (incompatible), mod:powah (incompatible), mod:ftbguilibrary (incompatible), mod:rangedpumps (incompatible), mod:potionofbees (incompatible), mod:wstweaks (incompatible), mod:bookshelf (incompatible), mod:uteamcore, mod:buildinggadgets (incompatible), mod:darkutils (incompatible), mod:morpheus (incompatible), mod:mekanismgenerators, mod:speedyhoppers (incompatible), mod:xnetgases, mod:toolkit (incompatible), mod:ftbteams (incompatible), mod:absentbydesign (incompatible), mod:refinedstorage (incompatible), mod:quartzchests (incompatible), mod:packmenu (incompatible), mod:animalcrops, mod:mcwbridges, mod:industrialforegoing (incompatible), mod:torchmaster (incompatible), mod:improved-stations (incompatible), mod:entangled, mod:biomesoplenty, mod:phosphor, mod:blur (incompatible), mod:valhelsia_structures (incompatible), mod:lollipop (incompatible), mod:ftbranks, mod:wtbw_lib, mod:simplylight (incompatible), mod:simplybackpacks (incompatible), mod:portality (incompatible), mod:curios (incompatible), mod:botania (incompatible), mod:patchouli (incompatible), mod:cloth-config2 (incompatible), mod:tanknull (incompatible), mod:angelring (incompatible), mod:libnonymous (incompatible), mod:elevatorid, mod:ftbultimine, mod:wirelessredstone, mod:naturesaura (incompatible), mod:mekanismtools, mod:mcwroofs, mod:cfm (incompatible), mod:computercraft (incompatible), mod:mcwfurnitures, mod:the_bumblezone, mod:yamda (incompatible), mod:speedyladders, mod:disenchanting (incompatible), mod:sdrp (incompatible), mod:quantumstorage (incompatible), mod:cyclic (incompatible), mod:inventorysorter (incompatible), mod:jmh (incompatible), mod:cucumber, mod:trashslot (incompatible), mod:torchslabmod, mod:mining_helmet (incompatible), mod:snad (incompatible), mod:itemfilters (incompatible), mod:jei (incompatible), mod:kubejs (incompatible), mod:longfallboots (incompatible), mod:lithium, mod:tesseract, mod:goblintraders, mod:mekanism, mod:polarizingbiomes (incompatible), mod:waystones (incompatible), mod:clumps (incompatible), mod:lightoverlay-forge (incompatible), mod:naturescompass (incompatible), mod:mcmc (incompatible), mod:goodnightsleep (incompatible), mod:additionalbars, mod:storagenetwork (incompatible), mod:dimstorage, mod:decorative_blocks, mod:botanypots (incompatible), mod:dungeoncrawl (incompatible), mod:ring_of_teleport (incompatible), mod:snowundertrees (incompatible), mod:bonsaitrees2, mod:mcjtylib (incompatible), mod:rftoolsbase (incompatible), mod:xnet (incompatible), mod:rftoolsstorage (incompatible), mod:travellersboots (incompatible), mod:packingtape, mod:mininggadgets (incompatible), mod:entitydetectors, mod:endercompass (incompatible), mod:rftoolspower (incompatible), mod:ftbchunks (incompatible), mod:campfiretorches, mod:forge (incompatible), mod:wtbw_core, mod:wtbw_tools, mod:ironchest, mod:craftingtweaks (incompatible), mod:cofh_core (incompatible), mod:ensorcellation (incompatible), mod:rftoolsutility (incompatible), mod:theoneprobe (incompatible), mod:distance (incompatible), mod:clockout, mod:playerplates (incompatible), mod:mousetweaks (incompatible), mod:titanium (incompatible), mod:moolands (incompatible), mod:usefulrailroads, mod:silentlib (incompatible), mod:wtbw_machines, mod:archers_paradox (incompatible), mod:soulshards (incompatible), mod:ding (incompatible), mod:rftoolsbuilder (incompatible), mod:miscadditions, mod:huntermod, mod:wtbw_decoration, mod:rats (incompatible), mod:gravestone, mod:ftbbackups (incompatible), mod:serverconfigupdater, mod:fastbench (incompatible), mod:storagedrawers (incompatible), mod:performant (incompatible), mod:doubleslabs, mod:harvest (incompatible), mod:jph (incompatible), mod:tubesreloaded (incompatible), mod:fastfurnace (incompatible), mod:transport, mod:appleskin (incompatible), mod:engineersdecor, mod:minetogether (incompatible), mod:moredragoneggs, mod:betterbedrockgenerator, mod:xlfoodmod, mod:waterworks (incompatible), mod:refinedstorageaddons (incompatible), mod:extremesoundmuffler (incompatible), mod:drawbridge, mod:defaultoptions (incompatible), kubejs:data_pack
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

* **Is it Repeatable?**: yes just entering the portal crashes the clients and then the server

* **Mod/s Affected**: rats mod

**Comment by Sunekaer** [comment]
Please test with version 1.6 or above
