### ISSUE TITLE
Omnia 1.15.0 crashes on load

### ISSUE THREAD

**Issue by Mike407** [FTBTeam/FTB-Omnia#123]
* **Modpack Version**: Omnia 1.15.0

* **Issue**: Using Linux Mint Linux Mint 19.3 Tricia  / OpenJdk 11
FTB-App : fresh install of FTBA_unix_1_0_9
Turing start appears
MineTogether (minetogether) encountered an error during the sided_setup event phase javax/xml/bind/annotation/adapters/HexBinaryAdapter

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/5751d2f1

* **Is it Repeatable?**: Yes, only removing minetogether from modfolder helps to startup

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Please test with Java 8

**Comment by Mike407** [comment]
New FTB Launcher forces Java11 to install, doesnt work with Java8
( Both are installed now)

Forced Omnia to start with Java8
Worked after reinstall of Omnia

Why the launcher forces Java11 if no ftb modpack accept Java11?

**Comment by Sunekaer** [comment]
Currently all mods packs need java 8, i cant answer for why the app uses 11 because i don't know
