### ISSUE TITLE
Mining Gadget Upgrades Lost / Disappeared

### ISSUE THREAD

**Issue by Dorsetsi** [FTBTeam/FTB-Omnia#124]
* **Modpack Version**: 1.5.0

* **Issue**: Mining gadget upgrades disappeared after disconnecting from server. I believe after the gadget was left in the Modification Table after log off from server. Server was being run locally on PC. The gadget had two modifications installed, Fortune Tier 2 and Efficiency Tier 5.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Tried to repeat and this time, the mining gadget itself disappeared from the modification table and was lost. Will try other combinations to try and repeat.

* **Mod/s Affected**: Mining Gadget

* **Known Fix**: N/A

**Comment by Sunekaer** [comment]
Could i get you to report it here: https://github.com/Direwolf20-MC/MiningGadgets/issues
As you can recreate this issue and therefore can easier work with the on getting it fixed
