### ISSUE TITLE
Player Damage Traps not dropping EXP

### ISSUE THREAD

**Issue by obachs971** [FTBTeam/FTB-Omnia#125]
* **Modpack Version**: 1.5.0

* **Issue**: Player Damage traps from Dark Utilities are not dropping EXP like it said it would.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/cac82745

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Dark Utilities

**Comment by Sunekaer** [comment]
Im guessing you killing mobs spawn by soul shard which doesn't drop exp
