### ISSUE TITLE
FTB Chunks minimap not showing claimed chunks

### ISSUE THREAD

**Issue by RealDimi** [FTBTeam/FTB-Omnia#126]
* **Modpack Version**: FTB Omnia 1.5.0

* **Issue**: 
The minimap is not showing the claimed Chunks

* **Is it Repeatable?**: 
the issue is permanent

* **Mod/s Affected**:  ftb-chunks-1.1.0.12

Would it be possible to show the claims on the minimap?

**Comment by Sunekaer** [comment]
Feel free to suggest it at https://github.com/FTBTeam/FTB-Chunks/issues
