### ISSUE TITLE
Omnia 1.5.0 Mekanism Digital Miner

### ISSUE THREAD

**Issue by GaltoPlays** [FTBTeam/FTB-Omnia#127]
* **Modpack Version**: Omnia 1.5.0

* **Issue**: I can't get the digital miner to respect it's filters. I can't seem to prevent cobble, dirt, gravel etc. from being mined. I am trying to do this in the mining world provided by the pack. Note I **DID** modify the pack by removing Rats and the Let's Mine Together mods but I did not add any mods. The mining world results seemed completely random. Sometimes I reset the miner and would get nothing at all and sometimes I get 20 straight cobble or dirt and sometimes I would get ore AND the things I was trying to prevent.I was unable to get the desired results in several different chunks. 

* **Link to Log or Crash File Paste**: No crash, just doesn't do what it is configured for.

* **Is it Repeatable?**: Yes but I did NOT test in the Overworld.

* **Mod/s Affected**: Mekanism

* **Known Fix**:

**Comment by Sunekaer** [comment]
Are you using the miner in a claimed area?
What are you putting in your filter?

**Comment by GaltoPlays** [comment]
I was not using it in a claimed chunk. I was playing in single player mode and I was in the mining dimension. I was trying inverted ItemStack filters to NOT mine cobble, gravel etc.

**Comment by Sunekaer** [comment]
Just use tag filter with forge:ores

**Comment by GaltoPlays** [comment]
Ok, I will try that, but that does not accomplish what I was trying to do, which was inverted ItemStack for stone, dirt, diorite etc. IE: pick up everything except the trash items I list. The inverted option may not work properly. I will test some stuff and report back. Is there a way to use the tag options to accomplish this?

**Comment by GaltoPlays** [comment]
Ok, so during this report, ver. 1.6.0 was released. Here are the results thus far. Using tags forge:stone forge:dirt forge:gravel and inverting the selection partially works. limestone basalt and marble all have tags forge:stone but are still mined. Adding these 3 items to ItemStack filters DID stop them. Since I don't know if this is the intended behavior I am not sure if it is a bug or not.

**Comment by Sunekaer** [comment]
Okay, thb i dont know if that is intended behavior you can try and ask them at https://github.com/mekanism/Mekanism/issues/
