### ISSUE TITLE
CTD/Launcher when loading and moving in a saved world - Omnia 1.5.0/1.6.0

### ISSUE THREAD

**Issue by gloomyMoron** [FTBTeam/FTB-Omnia#128]
* **Modpack Version**: 1.5.0/1.6.0

* **Issue**: Crash to Desktop/Launcher when moving/on world load. Issue is sporadic. Sometimes I can play for hours, other times it crashes within 5s of moving in the world. Seemingly almost always caused by movement. I added JourneyMap to the pack, but this was an issue ***before*** installing that. I've attempted reinstalls, downgrades, and changing Java arguments/memory allocation. Issue persists.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d744067e

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: N/A

* **Known Fix**: Temporary fix has been to downgrade and upgrade and/or load a backup, launch, and then restore the latest save, but eventually it winds up crashing all over again after some time.

**Comment by LatvianModder** [comment]
Can you please test if this version of FTB Chunks fixes it? https://jenkins.latmod.com/job/FTB-Chunks/16/

**Comment by gloomyMoron** [comment]
After a quick 30m test, it seems to work but it's hard to tell without further testing. Also, unrelated, but I've lost the ability to see how many haunches and how much saturation food gives you. I... don't know how or why that happened, though it is likely unrelated, I think. I might just be misremembering and you were never able to see that. >.>

**Comment by LatvianModder** [comment]
Thanks for testing! Let us know if it does happen to break eventually.
Appears to be missing Apple Skin mod by accident.

**Comment by gloomyMoron** [comment]
WIll do. There is another issue I'm having, but I'll make a new thread for that since it is entirely unrelated.
