### ISSUE TITLE
Plague Doctor spawning in Mining World

### ISSUE THREAD

**Issue by GaltoPlays** [FTBTeam/FTB-Omnia#129]
* **Modpack Version**: 1.6.0

* **Issue**: Plague Doctor spawning in Mining World. While testing some machines in the mining dimension a plague doctor from Rats spawned. I assume this is NOT the intended behavior.

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Rats

* **Known Fix**:

**Comment by Sunekaer** [comment]
The mining dim is just using a vanilla biome.
intended behavior, i dont know
https://github.com/Alex-the-666/Rats/issues
