### ISSUE TITLE
Silent's Mechanisms Alloy Smelter not displaying output recipes in JEI

### ISSUE THREAD

**Issue by gloomyMoron** [FTBTeam/FTB-Omnia#130]
* **Modpack Version**: 1.6.0

* **Issue**:  When attempting to view the recipes for alloys or recipes that the Alloy Smelter is capable of doing by left-clicking or pressing R on them in the inventory/JEI menu the recipes do not show. It shows the recipes that the Crusher accepts as well as the recipe for the machines themselves, just not the Alloy Smelter output recipes.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Silent's Mechanisms and/or Silent Lib

* **Known Fix**: Downgrading to 1.5.0 (it worked fine in this version but stopped working in 1.6.0)
________________
-[ Imgur Image](https://imgur.com/a/csGBW3j)

It used to work in JEI in Omnia 1.5.0 but it no longer does. I don't know if that's 'cause a thing got borked in a crash or because of the updated version of Silent Mechanisms used in 1.6.0 of the mod pack. The previous version of Silent's Mechanisms was **0.7.2+52**, and the previous version of Silent Lib was **4.6.0+48**. I've posted this issue on Silent's Mechanism's GitHub Issue tracker as well since I'm not sure if the fault is with the mod or the pack.

**Comment by Sunekaer** [comment]
Thanks for the information, we are looking to fixing the issue

**Comment by Sunekaer** [comment]
Pack update with fix pushed

**Comment by jakubnabrdalik** [comment]
Works like a charm. Thank you very much :)
