### ISSUE TITLE
Wither Skulls are uncraftable

### ISSUE THREAD

**Issue by gloomyMoron** [FTBTeam/FTB-Omnia#135]
* **Modpack Version**: 1.6.1

* **Issue**: [Attempting to craft Wither Skeleton Skulls but being unable to.](https://imgur.com/a/npS82IO)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6a3c3074

* **Is it Repeatable?**: Yes?

* **Mod/s Affected**: Presumably Wither Skeleton Tweaks, maybe Just Mob Heads

* **Known Fix**:
______________________

I cheated in 3 Wither Skeleton Skulls and trashed the 27 fragments I had and then cheated myself in 27 fragments, temporarily, to demonstrate my issue.

I don't know _why_ it'd be a problem, as I don't think anything I've added even touches wither skeleton recipes, but I've added _a few_ mods, but they're mostly UI stuff. Added mods:
* JourneyMap (because duh.)
* Just Enough Resources (which I'm going to remove because it wasn't as helpful as I'd thought it'd be. It just allows JEI to show at what levels resources are mine-able but requires custom values for non-vanilla ores.)
* Attribute Fix (because having armor that supersedes Vanilla Minecraft's values is pointless without this mod, as it caps at 30 unless funny tricks are used.)
* AnvilTweaks (just a QoL anvil mod that enhances their functionality by letting them retain their inventory slots and provides Config Options for turning off or modifying the Prior Work Penalty, adjusting the level cap before "Too Expensive!" is displayed, and make it so renaming an item always costs 1 level.)
* ExtraAnvils (for the giggles. It does what it says on the tin and adds a some extra anvils such as Stone, Gold, and Diamond.)
* Akashic Tome (because fuck having 15 manuals and books when you can have 1.)
* Music Player (to play music from YouTube and hard drive while playing)
* Overloaded Armor Bar (so it is possible to see the true value of armor.)
* CraftingCraft (it adds only _two_ items to the game, Portable Crafting Tables the both of them.)
* Inventory HUD+ (which I'm _mainly_ using to decrease the size of and move Minecraft's _**fucking annoying**_ Potion effects popups but also has other neat functionality such as an on screen Armor HUD showing the damage of your armor and such.)

Out of those the only one I think _might_ be the problem is CraftingCraft, but I don't see _why_ it would be. Doesn't touch any of the recipes and I wasn't even using the portable table to try and make the skulls. I was using an Improved Stations Crafting Table Slab and also tried a vanilla workbench.

Edit: Removing CraftingCraft had no effect.

**Comment by gloomyMoron** [comment]
I downloaded a new instance and tried it there... It worked. I think something got borked from when I was constantly updating an downgrading when I was having a previous issue. I'm gonna see if I can find the recipe files and check the configs to see what the cause might be.

Edit: I migrated the test save from the fresh instance into my modded instance and the recipe worked. Something defintely got borked elsewhere.

Re-Edit: Made a new test world on the modified pack (with CraftingCraft reinstalled) and the recipe works there too. Something is borked with my World save... is there a way to fix this?

**Comment by Sunekaer** [comment]
thb i have no clue whats causing your issue, i would recommend creating an on issue on the mods issue tracker maybe they have seen this before or have an idea to what you can try

**Comment by gloomyMoron** [comment]
Looks like, from some testing, something in the Level.dat or session.lock files got corrupted? But that doesn't make sense? Copied just those over to one of my test worlds and the recipe stopped working. Looks like I'm SOL.

**Comment by Sunekaer** [comment]
You can try and compare the content of the files.. but yeah i cant help because i don't know what the issue is
