### ISSUE TITLE
Anchor Upgrade Recipe

### ISSUE THREAD

**Issue by JRascagneres** [FTBTeam/FTB-Omnia#139]
Looks like anchor recipe is disabled? Not sure if this is bug or intentional?

**Comment by Sunekaer** [comment]
intentional

**Comment by JRascagneres** [comment]
Can I ask why? What's an alternative

**Comment by Sunekaer** [comment]
FTB chunks.
We try to only have one chunkloading solution

**Comment by JRascagneres** [comment]
Thanks. Is there a method to push the server limit up from 25 default of these then?

**Comment by Sunekaer** [comment]
you can ask here https://discord.gg/bPFfH6P
