### ISSUE TITLE
Mod recipe conflict

### ISSUE THREAD

**Issue by Marchedm** [FTBTeam/FTB-Omnia#14]
* **Modpack Version**:
 1,1,0

* **Issue**:
While playing I've noticed an issue between two mods Dark Utilities and Soul Shards Respawn. When smelting soul sand, soul glass from Dark Utilities is made now. There is now no way to make Vile Dust from Soul Shards Respawn due to new recipe conflict.

* **Is it Repeatable?**:
Yes

* **Mod/s Affected**:
Soul Shards Respawn

**Comment by Naxanria** [comment]
This is still an issue in 1.2.0
![image](https://user-images.githubusercontent.com/3246224/79432242-d6f9b880-7fcb-11ea-8dfe-24961ad01ae8.png)

**Comment by Sunekaer** [comment]
This is an issue with the app not overwriting the files, has been reported
