### ISSUE TITLE
v1.1.0 - Minetogether mod causes client to crash

### ISSUE THREAD

**Issue by grandrolf** [FTBTeam/FTB-Omnia#15]
* **Modpack Version**: 1.1.0

* **Issue**: Client crash when selecting (either wanting to open the link or to remove it from the list), "Click here to get one from CreeperHost!" in the multiplayer menu. Tested the old bugs, use normal chat/commands in-game or sleep in bed and that is not cause the issue anymore.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/802aad94

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: minetogether-1.15.2-4.0.0-Beta4.jar

* **Known Fix**: Disable the mod - or don't click the link (have not seen any other issues in-game connected to this version of the mod)

**Comment by Naxanria** [comment]
https://github.com/CreeperHost/CreeperHostGui/issues/221
