### ISSUE TITLE
Not authorized to download server files

### ISSUE THREAD

**Issue by EPostill** [FTBTeam/FTB-Omnia#18]
* **Modpack Version**: 1.1.0

* **Issue**: after clicking on a server type to download, a webpage opens with an Authorization failed error
This is the webpage I am directed to: https://api.modpacks.ch/public/modpack/undefined/46/server/windows
this one is for windows but all versions give the same error

* **Is it Repeatable?**: yes

**Comment by Sunekaer** [comment]
Hi, 

this issue needs to go to: https://github.com/FTBTeam/FTB-App/issues
