### ISSUE TITLE
MineTogether GDPR Decline crashes the game

### ISSUE THREAD

**Issue by ohhidenny** [FTBTeam/FTB-Omnia#2]
* **Modpack Version**:  1.0.0

* **Issue**: Declining the GDPR agreement in the MineTogether page crashes the game.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6b12259e

* **Is it Repeatable?**: yes

* **Mod/s Affected**: MineTogethermod

* **Known Fix**: accept the GDPR

**Comment by Naxanria** [comment]
This is fixed in new version of MineTogether. Will be in pack update.

**Comment by ohhidenny** [comment]
Nice, Thanks!

**Comment by Sunekaer** [comment]
Fixed been released

**Comment by jamierocks** [comment]
I've just downloaded the new version, and I don't ever get a GDPR screen anymore. Not on launch, or on clicking MineTogether.

![https://i.jamierocks.uk/J7GsTrGST1.png](https://i.jamierocks.uk/J7GsTrGST1.png)

**Comment by Jake-E** [comment]
We don't store PII. It's not needed.

**Comment by Sunekaer** [comment]
@jamierocks Why are you commenting on an issue there's been closed for a month?
Also not an pack issue, its an change in the mod as they don't store PII as Jake said, so they don't need the GDPthing.
