### ISSUE TITLE
I can't start Omnia server

### ISSUE THREAD

**Issue by markgyoni** [FTBTeam/FTB-Omnia#20]
* **Modpack Version**: 1.1.0

* **Issue**: When I trying to start the server with the start.bat file a cmd opens and it says every time that I want to agree to the Minecraft eula and I type in y and press enter and it closes but nothing happens
* **Link to Log or Crash File Paste**: No log file created

* **Is it Repeatable?**: Yes

**Comment by markgyoni** [comment]
And if I start the minecraft_server.1.15.2.jar file it starts but that's a vanilla server

**Comment by Sunekaer** [comment]
Double-click eula.txt to open it. If you’re on Windows, it should open in Notepad.
Read the contents of the file. Most importantly, read the Minecraft EULA.
If you agree to the EULA, change, eula=false to eula=true
Click Save to save eula.txt. Launch the server the way you did before, and your server should start.

**Comment by markgyoni** [comment]
Its already on  true

**Comment by markgyoni** [comment]
I know I need to do that

**Comment by Sunekaer** [comment]
Please upload your server log via https://paste.feed-the-beast.com/ and paste it here

**Comment by markgyoni** [comment]
No log is created when I start

**Comment by Sunekaer** [comment]
image of the console and eula.txt

**Comment by markgyoni** [comment]
https://imgur.com/a/xlhMkMW

**Comment by Sunekaer** [comment]
Did you press enter after the y?

**Comment by markgyoni** [comment]
Yes

**Comment by Sunekaer** [comment]
I just downloaded the server myself and it works just fine so this is not a pack issue, please create an issue at https://github.com/FTBTeam/FTB-App

**Comment by markgyoni** [comment]
I reinstalled it and it works! Thanks!

**Comment by FlygonC** [comment]
I'm having the same problem.
I've re downloaded and reinstalled the server many times, but the start.bat does not work.
I've set eula=true, and have tried many different way to get it running.
Am I missing a step, is there something else I need to download?

**Comment by markgyoni** [comment]
Your using 1.1.0 or 1.2.0?

**Comment by markgyoni** [comment]
In 1.2.0 there is the forge installer in the downloaded files. You nedd to install that to another folder and after it finished drag back the forge files and doible click the forge jar
