### ISSUE TITLE
game crash entangled block

### ISSUE THREAD

**Issue by popps73x** [FTBTeam/FTB-Omnia#24]
created entangled blocks and place in world.   Selected first block and then entangled to another.  render changes on the new blocks but not the original.  selected entangled block and tried to bind it to the first.  caused a crash and world will not load.  rendering error.

**Comment by Sunekaer** [comment]
Hi

Please attach the crash log.
https://faq.ftb.world/books/ftb-app/page/finding-your-client-logs

**Comment by Naxanria** [comment]
Not enough information, closing.
