### ISSUE TITLE
Map Replace

### ISSUE THREAD

**Issue by cptqrk** [FTBTeam/FTB-Omnia#27]
Not an issue per-se, but a suggestion/enhancement

Journey Map has a stable, fully featured version out for 1.15.2

Please replace Mappy.  That map mod is difficult to look at, and clunky as all get out to navigate/use.

I'm new to Github so I don't know how to change the tag.. sorry!

**Comment by Siveheart** [comment]
Please swap out Mappy. I absolutely hate it! It's clunky and unwieldy as previously stated. Another possible option for a different mod is VoxelMap since it's currently up to date.
