### ISSUE TITLE
Game crash when trying to sleep.

### ISSUE THREAD

**Issue by RCgaming77** [FTBTeam/FTB-Omnia#3]
* **Modpack Version**: 1.0.0

* **Issue**: Game crashes when i sleep in bed.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e8104405

* **Is it Repeatable?**: Yes i had it 4 times in row

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Hmmm very weird, we have been testing the pack for a while and havent had that issue happen before.
Have you changed anything to the pack?

**Comment by FLickerMeDead** [comment]
I had the same crash. When i enabled flying on the server it stopped crashing.

**Comment by Sabster** [comment]
I didn't have any issues with 1.0.0 - but 1.0.1 has crashed everytime when I sleep.

EDIT:  I enabled flying on my server - still crashes everytime I sleep.

**Comment by Sunekaer** [comment]
Crash log @Sabster

**Comment by Sunekaer** [comment]
Anyway the crash from RCgaming77's log should be fixed in newest version of the pack, for the rest of ya make an new issue with logs.

**Comment by Sabster** [comment]
@Sunekaer sorry, missed this:  Here ya go...  I had 4 of them back to back.

[crash-2020-04-04_02.57.55-client.txt](https://github.com/FTBTeam/FTB-Omnia/files/4440378/crash-2020-04-04_02.57.55-client.txt)
[crash-2020-04-04_03.08.57-client.txt](https://github.com/FTBTeam/FTB-Omnia/files/4440379/crash-2020-04-04_03.08.57-client.txt)
[crash-2020-04-04_03.25.08-client.txt](https://github.com/FTBTeam/FTB-Omnia/files/4440380/crash-2020-04-04_03.25.08-client.txt)
[crash-2020-04-04_03.37.20-client.txt](https://github.com/FTBTeam/FTB-Omnia/files/4440381/crash-2020-04-04_03.37.20-client.txt)
