### ISSUE TITLE
[Bug] Installer.jar cannot be installed.

### ISSUE THREAD

**Issue by James-Ingram** [FTBTeam/FTB-Omnia#32]
* **Modpack Version**: 
Client - 1.2.0

* **Issue**: 
Any attempt to install the modpack causes the pack to give the below message, the `retry?` button appears to have no effect.

* **Link to Log or Crash File Paste**: 
![image](https://user-images.githubusercontent.com/17910502/79384584-12aa6900-7f5f-11ea-8489-8052da609abd.png)

* **Is it Repeatable?**: Uncertain, having seen no others reporting this error, I could be an edge case, however I was on a fresh install, having never used the launcher before.

* **Mod/s Affected**: 
N/A

* **Known Fix**: 
N/A

**Comment by AKTheKnight** [comment]
This should now be fixed, try again and let us know if it doesn't work :)

**Comment by masonbesmer** [comment]
broken again same error
