### ISSUE TITLE
Doesn't start after update 1.2.0. Something with MC Configuration.

### ISSUE THREAD

**Issue by zo1tuz** [FTBTeam/FTB-Omnia#33]
* **Modpack Version**: 1.2.0

* **Issue**: Minecraft unable to start

* **Link to Log or Crash File Paste**: 
![Capture](https://user-images.githubusercontent.com/63751232/79386568-9e75c280-7f6a-11ea-9904-d4ce21ff4414.PNG)

* **Is it Repeatable?**: Yes. Everytime I try to start.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by zo1tuz** [comment]
Also unable to gather details when editing the Installation in Minecraft Launcher:
![Capture2](https://user-images.githubusercontent.com/63751232/79387801-9880e100-7f6c-11ea-8522-c504c19a4d49.PNG)

**Comment by Sunekaer** [comment]
Hi 

Please repor this at https://github.com/FTBTeam/FTB-App/issues
