### ISSUE TITLE
Visual Conflict from XNet Controller GUI over JEI Bookmarks

### ISSUE THREAD

**Issue by Trouss33** [FTBTeam/FTB-Omnia#34]
* **Modpack Version**: 1.2.0

* **Issue**: When opening the XNet controller GUI the left hand side overlaps the JEI Bookmarks making the interface look cluttered. 

* **Link to Log or Crash File Paste**: No crash log, visual bug only. 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: XNet and JEI Bookmarks

* **Known Fix**: Not Known

**Comment by Trouss33** [comment]
This was also the case for the pack version prior.

**Comment by Trouss33** [comment]
This was also the case for the previous pack version.

**Comment by Naxanria** [comment]
https://github.com/McJtyMods/XNet/issues/403
