### ISSUE TITLE
Massive lag in main menu and possibly everywhere else

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Omnia#35]
* **Modpack Version**: 1.2.0

* **Issue**: Main menu and basically everything lags and CPU usage is nearly 100%

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: MineTogether

* **Known Fix**: Remove MineTogether until it's fixed

![](https://i.latvian.dev/pc/2020-04-16_04.36.05.png)

**Comment by vertex101** [comment]
i run the modpack with 6gb of ram and this works fine for me so it might be a ram issue

https://i.imgur.com/uH2jvKa.png

---UPDATE---

after doing some more research into this found out the minimum the modpack can do is 4gb of ram anything under it will not load up a SP world and causes the very high CPU usage

**Comment by Sunekaer** [comment]
@LatvianModder 
How much ram do you have assigned?

**Comment by EyJiL** [comment]
How do you assign more ram ?

**Comment by Sunekaer** [comment]
@EyJiL 
https://faq.ftb.world/books/ftb-app/page/changing-instance-settings

**Comment by Sunekaer** [comment]
Issue is that 3GB is not enough.
With 3GB ram you so close to the limit, that the garbage collector is running ALL the time.

tldr 
Assign more ram
