### ISSUE TITLE
Game crash when joining a server

### ISSUE THREAD

**Issue by EyJiL** [FTBTeam/FTB-Omnia#38]
* **Modpack Version**: 1.2.0

* **Issue**: My game crash when i'm joining a server

* **Is it Repeatable?**: everytime I play the game

* **Mod/s Affected**: no idea

* **Known Fix**: no idea

**Comment by Sunekaer** [comment]
Crash log please
https://faq.ftb.world/books/ftb-app/page/finding-your-client-logs

**Comment by EyJiL** [comment]
https://paste.feed-the-beast.com/view/c9270551

**Comment by Sunekaer** [comment]
this is not a crash log?

**Comment by Naxanria** [comment]
Not enough information, closing.
