### ISSUE TITLE
You're shipping the FTB dev server address in Direct Connection

### ISSUE THREAD

**Issue by AKTheKnight** [FTBTeam/FTB-Omnia#4]
V 1.0.1
Repeatable.
Fix: Remove it from Direct Connection

![image](https://user-images.githubusercontent.com/7502848/78457085-b06c8100-769f-11ea-80d8-7d7016875c1e.png)

**Comment by Sunekaer** [comment]
Thanks,
Literally dont how that gets included in the pack
