### ISSUE TITLE
MP Server crashes when creepers explode, 2/3 times

### ISSUE THREAD

**Issue by btornatore** [FTBTeam/FTB-Omnia#40]
* **Modpack Version**: 1.2.0

* **Issue**: server will usually crash when creepers explode

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f7bb0fb3
* **Is it Repeatable?**: yes

* **Mod/s Affected**: unsure

* **Known Fix**: dont go near creepers

**Comment by Naxanria** [comment]
This is a Watchdog crash, basically a tick took to long so it stopped the server.
Could you post the log files, there might be more info on what is actually causing the server to hang.

**Comment by Sunekaer** [comment]
Asked for information not provided. closing issue
