### ISSUE TITLE
[1.2.0] Server crashes on player death

### ISSUE THREAD

**Issue by Xalaxis** [FTBTeam/FTB-Omnia#41]
* **Modpack Version**: 
1.2.0
* **Issue**: 
When players die (not sure if 100%, but most of the time), the server crashes.
* **Link to Log or Crash File Paste**: 
[crash-2020-04-17_20.23.49-server.txt](https://github.com/FTBTeam/FTB-Omnia/files/4495273/crash-2020-04-17_20.23.49-server.txt)
[crash-2020-04-17_21.02.38-server.txt](https://github.com/FTBTeam/FTB-Omnia/files/4495274/crash-2020-04-17_21.02.38-server.txt)

* **Is it Repeatable?**: 
Yes, by having a player die from a mob.
* **Mod/s Affected**: 
It appears to be caused by Just Player Heads going off the stack trace.  The version reported by the crash log is 1.0

**Comment by Xalaxis** [comment]
This may be related to #40 , as there also appear to be crash logs from the same day with tick crashes, but this was not observed directly.

[crash-2020-04-17_20.24.53-server.txt](https://github.com/FTBTeam/FTB-Omnia/files/4495280/crash-2020-04-17_20.24.53-server.txt)
[crash-2020-04-17_21.03.40-server.txt](https://github.com/FTBTeam/FTB-Omnia/files/4495281/crash-2020-04-17_21.03.40-server.txt)

**Comment by Sunekaer** [comment]
Can you check if its an issue with version 1.3.0?
No one else have reported this, and the logs doesn't give any useful info

**Comment by Xalaxis** [comment]
Certainly, I'll check and report back.

**Comment by Xalaxis** [comment]
I've updated my server today, so I hope to do some testing this weekend.

**Comment by Sunekaer** [comment]
Please reopen the issue, if you still have issues
