### ISSUE TITLE
MineTogether - No curse project ?

### ISSUE THREAD

**Issue by HaoSs07B** [FTBTeam/FTB-Omnia#42]
* **Modpack Version**: 1.2.0

* **Issue**: There's no CurseForge  project witch is needed to register a server on the MineTogether tab.

* **Link to Log or Crash File Paste**: -- 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: MineTogether 

* **Known Fix**: None

**Comment by Sunekaer** [comment]
It doesnt need an curse project it should work just fine, as long as the pack is installed via the FTB App

**Comment by LemADEC** [comment]
My server doesn't show in the list. What's the way to publish it nowadays?

**Comment by Sunekaer** [comment]
please report at https://github.com/CreeperHost/CreeperHostGui/issues
