### ISSUE TITLE
mining turtle

### ISSUE THREAD

**Issue by oliplays58** [FTBTeam/FTB-Omnia#44]
i put all the code in then i get to the point where it asks if i want chests or ender chest or torches and it wont let me choose anything

**Comment by Sunekaer** [comment]
Hi 

This can both be an issue with your code or the turtle, best bet would be try at https://github.com/SquidDev-CC/CC-Tweaked/issues
And link them the code also

**Comment by oliplays58** [comment]
the code i used is
pastebin get 6qmBBlpz Miner
miner
then i choose my options
but it wont let me choose after that
