### ISSUE TITLE
Mekanism Digital Miner Stops immediately once mining

### ISSUE THREAD

**Issue by EPostill** [FTBTeam/FTB-Omnia#45]
* **Modpack Version**: 1.2.0

* **Issue**: Digital miner from mekanism immediately goes to 0 blocks once started

* **Is it Repeatable?**:  yes, I've tried with and without filters

* **Mod/s Affected**: Mekanism

**Comment by EPostill** [comment]
Additionally I noticed that although the RFTools builder will cycle through the blocks it also does not mine any of them, nor consume power. However, the other type of quarry works fine (can't remember the name of the mod W--- machines)

**Comment by Naxanria** [comment]
Did you claim the area? In that case you need to add them to your allies. They use a fake player (shown in the ally list with [name]). Add them to your allies and they should be able to mine.

**Comment by EPostill** [comment]
I haven't tested but I'm almost certain that's it. Thank you
