### ISSUE TITLE
Server installer doesn't automatically install Forge? Manual install still does not work.

### ISSUE THREAD

**Issue by FlygonC** [FTBTeam/FTB-Omnia#46]
* **Modpack Version**: 1.2.0

* **Issue**: The server installer leaves me with a Forge installer instead of installing automatically. Running the forge installer for a server in the same folder still doesn't allow the server to run from the start.bat

* **Link to Log or Crash File Paste**: 
[installer.log](https://github.com/FTBTeam/FTB-Omnia/files/4513449/installer.log)

* **Is it Repeatable?**: Yes

**Comment by Naxanria** [comment]
This looks like an issue with FTB App, not the pack. Please report the issue here https://github.com/FTBTeam/FTB-App/issues
