### ISSUE TITLE
FTB Omnia 1.15.2 world load freeze

### ISSUE THREAD

**Issue by Iplay2L8** [FTBTeam/FTB-Omnia#52]
pack loads and on world creation freezes at 0%. 
repeatable=yes
solution= pack installs with 3.00GB  instance memory as defult
I increased to 8.00GB and loaded fine. 
Change of default instance memory will solve. Or note in overview that instance memory needs to be increased.

**Comment by Sunekaer** [comment]
Hi the pack should install with 4gb as default, if it don't please report at https://github.com/FTBTeam/FTB-App/issues
