### ISSUE TITLE
Mining gadget + ultimine = destroys all blocks with no drops, uses no energy

### ISSUE THREAD

**Issue by andyglover** [FTBTeam/FTB-Omnia#54]
* **Modpack Version**: FTB Omnia 1.2.0

* **Issue**: When using the mining gadget's right-click mining function, along with any mode of FTB Ultimine, all blocks selected by ultimine are immediately destroyed, leaving no drops to pick up, and consuming no energy from the mining gadget's reserve.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Mining Gadgets 1.3.5, FTB Ultimine 1.0.8.4

* **Known Fix**: none

**Comment by kylania** [comment]
This is repeatable for me as well using the same versions.
