### ISSUE TITLE
Furnace ui not opening/ un-usable

### ISSUE THREAD

**Issue by kbaran0105** [FTBTeam/FTB-Omnia#55]
* **Modpack Version**: 1.2.0

* **Issue**: When I try to use the Furnace, there will not be a Gui that opens, and I cannot use it

* **Link to Log or Crash File Paste**: None.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Unknown

* **Known Fix**: Unknown

**Comment by Sunekaer** [comment]
Which furnace? log?

**Comment by kbaran0105** [comment]
It is the vanilla furnace

**Comment by Naxanria** [comment]
Could you give us the log? https://faq.ftb.world/books/ftb-app/page/finding-your-client-logs
Then we can maybe find out why that is happening.

**Comment by kbaran0105** [comment]
Here is the log
https://paste.feed-the-beast.com/view/eda45338

**Comment by Naxanria** [comment]
I dont see anything in the log that indicates it might be causing it :/

**Comment by Sunekaer** [comment]
Are you in a claimed area?

**Comment by kbaran0105** [comment]
> Are you in a claimed area?<
Yes

**Comment by Sunekaer** [comment]
Does it work out site claim?
Is it claimed by you or another?

**Comment by kbaran0105** [comment]
I does work outside of claim, and is in a claim made by me

**Comment by Sunekaer** [comment]
Can you open other machines?
Can you show me your team settings
