### ISSUE TITLE
Attempting to go to the end while wearing an angel ring teleports you back to spawn

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Omnia#56]
Mod pack version: 1.2.0

Issue: Attempting to go into end portal while having angel ring on teleports you back to spawn

Link to log or paste file: N/A

Is it repeatable: Possibly, not sure if it only affects me, I was also on a server at the time

Mod/s affected: Angel ring

![Cantgotoend](https://user-images.githubusercontent.com/63080585/80751803-0f32e800-8af0-11ea-81a6-7964e26e250b.gif)

**Comment by Naxanria** [comment]
Do you have a log? https://faq.ftb.world/books/ftb-app/page/finding-your-client-logs
Then we can see what might be causing it

**Comment by ghost** [comment]
https://paste.feed-the-beast.com/view/0736d943 is this what you were looking for?

**Comment by ghost** [comment]
I can't seem to replicate the issue anymore, it seems it might have just been some weird one time glitch or something.
