### ISSUE TITLE
Crash upon startup - GLFW error 65539: Invalid key 4

### ISSUE THREAD

**Issue by nepitunes** [FTBTeam/FTB-Omnia#57]
* **Modpack Version**: FTB Omnia 1.2.0

* **Issue**: I try to load FTB Omnia and it crashes with this message (below). The window will generally crash with (for example) 10 tries but sometimes I'll have a lucky attempt that will let me in and play the game. I am up-to-date with Windows, both drivers including GeForce one are all up-to-date because I checked after I got this message. Please let me know if I'm doing something wrong.
![2020-05-02 (25)](https://user-images.githubusercontent.com/64739686/80917247-a8af0380-8d55-11ea-9988-67275a5e775f.png)

* **Link to Log or Crash File Paste**: Latest log https://paste.feed-the-beast.com/view/286520cd

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: FTB Omnia (only one I play)

* **Known Fix**: N/A

**Comment by Naxanria** [comment]
If you have anything like a controller plugged in, try unplug it and start it again?
Outside that, this is not an error with the pack we can do anything about.

**Comment by P2ON** [comment]
Hello, I have the same issue. My drivers/windows are up-to-date too. I don't have controller plugged in either. 

To launch the mod, I have to uninstall and redownload if I want to play. 
It's not too long to download, but the biggest problem are the server list and my in-game config/binds are all reset. Not long either. But I must have done it at least 40 times so it's kinda boresome sometimes :) 

Hope there will be a fix someday. 

I just wanted to share my issue that we have in common with the OP :)

**Comment by Sunekaer** [comment]
try delete mouse.4 and any other offending keys if more mouse buttons cause issues too, from options.txt in your instances folder.

**Comment by P2ON** [comment]
I tried without my usual binding and it work now. The issue was from my mouse.4 and mouse.5 binding :) 

Thank you Sunekaer for taking the time to answer. Quick, simple and efficient.

Best regards

**Comment by Sunekaer** [comment]
Your welcome, this was a new one to me too :)
