### ISSUE TITLE
Backpacks Not Craftable

### ISSUE THREAD

**Issue by Siveheart** [FTBTeam/FTB-Omnia#58]
**Modpack Version**: 1.2.0

* **Issue**: The recipe for the basic backpack does not appear to be craftable.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Backpacks

* **Known Fix**: None

**Comment by Sunekaer** [comment]
Could you show an example? in our testing we was able to

**Comment by Siveheart** [comment]
I'll try it again and post a picture once I'm in-game. I just downloaded a fresh install trying to fix another issue.

**Comment by Siveheart** [comment]
![image](https://user-images.githubusercontent.com/14877581/81113462-e478d300-8ee5-11ea-8e7f-451bd78d2c21.png)

**Comment by kylania** [comment]
The recipe calls for White Dye not just Bonemeal.  Are you using Bonemeal in that image?

**Comment by Siveheart** [comment]
That time it was bonemeal since that what JEI had said would work, but I also tried it with white dye and had the same issue. I'll post another picture once I'm in game again.

**Comment by Siveheart** [comment]
And now it's working again, but my map has deleted itself and JEI won't unhide. XD I just love testing packs. Lol. I guess the new install fixed at least this issue? I don't know, but it's working now. Thank you.
