### ISSUE TITLE
JEI Setings Key Not Functioning

### ISSUE THREAD

**Issue by Siveheart** [FTBTeam/FTB-Omnia#59]
**Modpack Version**: 1.2.0

* **Issue**: If you click on the settings button within JEI, nothing happens

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: JEI

* **Known Fix**: None

**Comment by Naxanria** [comment]
That is correct, it has not been implemented yet.
