### ISSUE TITLE
v1.2.0 MineTogether Crash on reloading servers after long period of idle time on multiplayer screen

### ISSUE THREAD

**Issue by koalalord9999** [FTBTeam/FTB-Omnia#60]
* **Modpack Version**:  1.2.0 

* **Issue**:  I sit idle on my multiplayer screen over night a lot of times, so I don't have to reload my game, and when I press the green refresh icon, it crashes. Also happens after logging out of a server, if the refresh button is pressed.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/d9e561e2 

* **Is it Repeatable?**:  takes some undetermined amount of time on multiplayer screen, but after that time, reloading crashes the client 

* **Mod/s Affected**:  MineTogether | minetogether-1.15.2-4.0.0-Beta5.jar 

* **Known Fix**:  optional; if you know of a fix please let me know! Thanks

**Comment by kylania** [comment]
I've had this happen to me as well, just about an hour ago actually.  Pretty sure it's a specific to minetogether bug rather than an Omnia general bug though.  Using the upgraded beta 5 version you are too.

**Comment by Naxanria** [comment]
https://github.com/CreeperHost/CreeperHostGui/issues/224
This is same issue as #19 
This does not seem to be fixed in beta 5 (as that is current version in Omnia)
