### ISSUE TITLE
JEI Hidden, Can't Unhide

### ISSUE THREAD

**Issue by Siveheart** [FTBTeam/FTB-Omnia#61]
* **Modpack Version**: 1.2.0

* **Issue**: JEI has hidden itself and keys to unhide it are not working. I've tried assigning different keys and reinstalling, but it didn't fix the issue.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: JEI

* **Known Fix**: Unknown

**Comment by Sunekaer** [comment]
The default ctrl + o works fine for me
What res you playing at? Because if the window is too small JEI wont show

**Comment by Siveheart** [comment]
I've been playing fullscreen on a 15.5 inch laptop.

**Comment by Siveheart** [comment]
It was showing and then it just randomly stopped showing up. If I create a new world, it will show up in the new world, but not the world that I've been using.

**Comment by Sunekaer** [comment]
Hmm, i have never seen this issue before could you report it at https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue maybe they can help you

**Comment by Siveheart** [comment]
https://github.com/mezz/JustEnoughItems/issues/1961
