### ISSUE TITLE
Crashing server by left clicking glass with cyclic build tool

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#62]
1.2.0 server and client side

Item cyclic:build_septer and cyclic:offset_scepter. It seems when I go to shift left click minecraft:glass it crashes the server and restarts auto but just sends the player to the menu. a upon returning into the world I was able to left click cyclaing through the various options of the cyclic:offset_scepter and use it like normal, the cyclic:build_scepter I do not know if I was using it wrong but it did not want to right click on anything even tho it says it has glass as its choice.

I looked to see if client side had a crash report and it did not unfortunately.
https://paste.feed-the-beast.com/view/387a4124

Yes I went into creative this time and tried it with a new cyclic:offset_scepter and yes it was.

I am assuming it is this one, Cyclic-1.15.2-0.3.2

I do not know of a fix sorry.

**Comment by Sunekaer** [comment]
https://github.com/Lothrazar/Cyclic/issues/1400

**Comment by Sunekaer** [comment]
Should be resolved in newer version of the mod
