### ISSUE TITLE
Version 1.3.0 doesn't start

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Omnia#63]
* **Modpack Version**:1.3.0

* **Issue**: error installing modpack

* **Link to Log or Crash File Paste**: no log files that I can find

* **Is it Repeatable?**: yes, every time I try to install the game. A friend of mine who I've been playing with has the same issue.

* **Mod/s Affected**: none specific that I've seen.

* **Thing's I've tried**: Uninstalling 1.2 entirely and trying to install 1.3 didn't work. Uninstalling all modpacks and the launcher and then reinstalling from scratch also didn't work.

**Comment by JacobDV96** [comment]
Having the same issue. For me, it tries downloading https://apps.modpacks.ch/versions/net/minecraftforge/forge/1.15.2-31.1.77/forge-1.15.2-31.1.77-installer.jar but neither this file nor the parent folder exist.

**Comment by Sunekaer** [comment]
The issue has been fixed, if you still have the issue its do to caching, please wait like 30min and try again

**Comment by GnarledBeard** [comment]
It has been three hours and this issue still persists. 
I tried completely uninstalling FTBA and reinstalling, how ever still getting a 404 out of creeperhost for the .77 version of forge.
