### ISSUE TITLE
Multiple users cannot launch the game after 1.3.0 update

### ISSUE THREAD

**Issue by chadbob** [FTBTeam/FTB-Omnia#64]
* **Modpack Version**: 1.3.0

* **Issue**: We updated to 1.3.0, Press play the Minecraft launcher opens and when you press Play you get a "Sorry, unable to start Minecraft, please check your configuration."

* **Link to Log or Crash File Paste**: I cannot find which error log has this information

* **Is it Repeatable?**: yes several users of my server had this issue

* **Mod/s Affected**: All

* **Known Fix**: No idea

**Comment by Sunekaer** [comment]
Please report at https://github.com/FTBTeam/FTB-App/issues This is an issue with the launcher and not the pack
