### ISSUE TITLE
FTB Omnia SP World Crash

### ISSUE THREAD

**Issue by oiGhostt** [FTBTeam/FTB-Omnia#67]
* **Modpack Version**: 1.3.0

* **Issue**: I updated from 1.2.0 to 1.3.0 and crashed. I tried reinstalling the pack after deleting it completely to retry and it still had the same crash. I get to the singleplayer tab and when I open or create a world it says loading world and does the 100% loading animation and then it says saving world and closes.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2da89159

* **Is it Repeatable?**: Yes, just by launching game and opening or creating a singleplayer world

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
I havent been able to recreate this issue, does it also happen on a fresh install of the pack?

**Comment by oiGhostt** [comment]
Yea I reinstalled pack and it still happened. I am going to check my antivirus to see if that is blocking anything. Other than that all I can think of is that i was messing with java versions the other day but isnt java in the ftb files so that wouldnt matter?

**Comment by oiGhostt** [comment]
Well I reinstalled the pack completely and disabled my antivirus when setting up the launcher and installing the pack. It works now though long story short. I thought it was weird my friend got the launcher and installed it no problem. But thanks for your time either way!

**Comment by Sunekaer** [comment]
Glad to hear you got it to work!
