### ISSUE TITLE
*Improved-Stations* are unusable when paired with *doubleslabs*

### ISSUE THREAD

**Issue by EspieBodespie** [FTBTeam/FTB-Omnia#68]
* **Modpack Version**: 1.3.0

* **Issue**: When *improved-stations*' slab stations are placed with any other slabs creating a double slab from the *doubleslabs* mod, the station is unusable and any items inside pop out.

* **Link to Log or Crash File Paste**: No crash/log file created.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: I believe it's the *doubleslab* mod.

* **Known Fix**: No know fix yet, but here is a quote from the *doubleslabs* developer in regards to this bug.

![Doubleslab-Dev-Quote](https://user-images.githubusercontent.com/51254988/81509049-d5ff3280-92bc-11ea-9b0c-7ae9c81313ab.png)

Here are some screenshots to visually explain the bug.

![slab-stations](https://user-images.githubusercontent.com/51254988/81508910-d64afe00-92bb-11ea-8a27-0fbe04a1d14b.png)
![slab-stations-as-doubleslabs](https://user-images.githubusercontent.com/51254988/81508913-d945ee80-92bb-11ea-997d-94e8f97669d5.png)
![slab-stations-with-stone-slab](https://user-images.githubusercontent.com/51254988/81508914-db0fb200-92bb-11ea-8af0-9ef83d4eb914.png)

**Comment by Sunekaer** [comment]
Thanks for the information, wasn't aware of this issue

**Comment by Sunekaer** [comment]
improved-stations' slab was blacklisted in 1.4.0
