### ISSUE TITLE
FTB utilities- Backup is not making backup folder

### ISSUE THREAD

**Issue by Iplay2L8** [FTBTeam/FTB-Omnia#7]

**Comment by Iplay2L8** [comment]
in game message that game may lag for backup. says backup complete. No backup folder has been made in the instance folder which FTBA direct you to when you select open folder. cannot find anywhere else on hard drive. 
![Capture](https://user-images.githubusercontent.com/20152346/78620579-65dd3700-784e-11ea-8a32-897608bcf165.PNG)

**Comment by Naxanria** [comment]
Do you have a log? Might help tracking down why it is not working.

**Comment by Sunekaer** [comment]
Have you had the world open for more than 2 hours in one go?
The backup is done 120 min after you open the world
