### ISSUE TITLE
Clicking on Snad in Mod List crashes the game

### ISSUE THREAD

**Issue by Venom31** [FTBTeam/FTB-Omnia#70]
* **Modpack Version**: 1.3.0

* **Issue**: Accessing mod list, then navigating to and left clicking on Snad leads to a game crash.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/5787eaa3

* **Is it Repeatable?**: Yes, you can do it from the main menu of from the loaded world.

* **Mod/s Affected**: Possibly Snad 1.8.5.10a, or whatever is responsible for displaying the mod list.

* **Known Fix**: None.

**Comment by Sunekaer** [comment]
Does it happen with any other mods?

**Comment by Sunekaer** [comment]
reported https://github.com/lazynessmind/Snad/issues/7

**Comment by Venom31** [comment]
I clicked on a lot of ones above Snad, not a lot of them below, just 1 or 2, it was fine. There's a lot of them, so didn't click them all, sorry.

**Comment by Venom31** [comment]
Clicked on them all today. No other mods exhibit crashes.

A bit off-topic: I noticed that search in mod list only works when the scroll bar is at the upper position, don't know if that's intended.
