### ISSUE TITLE
Memory usage is absurd

### ISSUE THREAD

**Issue by HalJordan** [FTBTeam/FTB-Omnia#71]
It doesn't matter what I set the limit to, before long it eats up well past that limit until it's exhausted every spare byte of memory on my system(16 GB).

**Comment by Sunekaer** [comment]
Hi

I play with 5GB assigned and my ram use is at 55% to 74% in SP
How much do you have assigned?
You playing in SP or MP?
Do you have a lot of chunk loaded things?

**Comment by HalJordan** [comment]
This was before I turned on any chunk loading. I had set the limit to 5GB,
since it complained about the 3GB the launcher set by default.

It's blowing way past that and isn't 14 GB well over double.

**Comment by AngelicBeatz** [comment]
I have a server up and it's using about 8gb out of 20gb for just 3 people, would be nice if it wasnt so high but heck.

**Comment by Sunekaer** [comment]
Launcher minimum such be on 4GB, that is the client minimum, i run my client at 5.
Our test server we ran at 6gb for 8 people and it was running fine
