### ISSUE TITLE
Both Good Nights Sleep and Moolands mod causing server halt.

### ISSUE THREAD

**Issue by Ratomas** [FTBTeam/FTB-Omnia#72]
Minecraft 1.15.2
FTB Omnia 1.3.0

Both Good Nights Sleep and Moolands mod causing server to crash, forcing a complete restore from backup. Both causing the crash upon return to the overworld.

**Comment by Naxanria** [comment]
Do you have a crashreport and logs? Cant do much without them

**Comment by Ratomas** [comment]
That's the thing... Nothing in the logs to show why. The server just halts and gives connection timeout every time I try to reconnect, till I restore from backup, but it only happens when returning from either one of those dimensions. I will try to get a log for you, but like I said it tells nothing.

**Comment by Ratomas** [comment]
[debug.log](https://github.com/FTBTeam/FTB-Omnia/files/4623491/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Omnia/files/4623492/latest.log)

Here are both the logs from the server. Let me know if you need anything else. After the last log entry nothing else is written till I restore the server from backup.

**Comment by Sunekaer** [comment]
Please use https://paste.feed-the-beast.com/ for the logs
