### ISSUE TITLE
Modpack stalls during initialisation

### ISSUE THREAD

**Issue by ash1066** [FTBTeam/FTB-Omnia#73]
* **Modpack Version**: 1.30

* **Issue**: The modpack boots to the forge loading screens with the mojang logo on it, but stalls at the Atlas stitching bit for shulker box textures. It just occaisionally takes a few extra mega bytes of ram every 2 or 3 seconds, then resets whenever the memory usage gets to about 40% or 3800 mb each then drops down to somewhere in the 1000 megabyte range. It continues like this for as long as I leave it.

* **Link to Log or Crash File Paste**: I dont have one.

* **Is it Repeatable?**: Yes, i have reinstalled the modpack twice and the issue persists.

* **Mod/s Affected**: N/A

* **Known Fix**: I wish I did

**Comment by Naxanria** [comment]
Could you link the logs? https://faq.ftb.world/books/ftb-app/page/finding-your-client-logs

**Comment by mmaynard** [comment]
Ran into the exact problem. Tried closing the launcher 4 times and kept getting stuck in the same spot. Restarting my PC cleared the issue up. Here is a log of the issue though.

[2020-05-15-2.log](https://github.com/FTBTeam/FTB-Omnia/files/4634979/2020-05-15-2.log)
