### ISSUE TITLE
Goblin Trader dies after every hit and respawns with updated health and his health reaches 0 while still alive.

### ISSUE THREAD

**Issue by EspieBodespie** [FTBTeam/FTB-Omnia#74]
* **Modpack Version**: 1.3.0

* **Issue**: Goblin Trader uses the dying animation after every hit only to respawn with it's updated health.  On his health bar, it will show 0 hearts while he is still alive.

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes.  Just hit a goblin trader.

* **Mod/s Affected**: *goblintraders* by MrCrayfish

* **Known Fix**: No known fix.

Here's a video showing the bug.
https://youtu.be/n0GApDOcnwU

**Comment by Ratomas** [comment]
Sunekaer this is not a bug, no update coming to fix this. [Goblin Trader dies after every hit and respawns with updated health and his health reaches 0 while still alive #16](https://github.com/MrCrayfish/GoblinTraders/issues/16)

**Comment by Sunekaer** [comment]
Not a bug. You're actually knocking the goblin over. Their health doesn't not reset.
