### ISSUE TITLE
Buggy interactions with Torch Slabs Mod.

### ISSUE THREAD

**Issue by EspieBodespie** [FTBTeam/FTB-Omnia#76]
* **Modpack Version**: 1.3.0

* **Issue**: There are a few buggy interactions with the *Torch Slabs Mod*

Preface, Torches are placed on the bottom half in vanilla and lanterns are placed on the top half in vanilla
![preface](https://user-images.githubusercontent.com/51254988/81851856-f9b9b700-950e-11ea-9b9c-4c6c2b7a05f4.png)

1) Torches placed on the top half of a block will be destroyed if a half slab is placed on the bottom half of the block above it.
![Torches_1](https://user-images.githubusercontent.com/51254988/81851873-ffaf9800-950e-11ea-8e28-55490b3fff12.png)
![Torches_2](https://user-images.githubusercontent.com/51254988/81851874-00482e80-950f-11ea-82d5-7291c6e4cbbe.png)

2) Lanterns placed on the bottom half of a block will clip through a half slab placed on the top half of the block below it and will not be destroyed, but *WILL* be destroyed if a full block is placed below it.
![Lantern_1](https://user-images.githubusercontent.com/51254988/81851895-06d6a600-950f-11ea-8054-31b54964275a.png)
![Lantern_2](https://user-images.githubusercontent.com/51254988/81851896-076f3c80-950f-11ea-852c-f49cae89606a.png)
![Lantern_3](https://user-images.githubusercontent.com/51254988/81851898-076f3c80-950f-11ea-9524-4eb447e1475e.png)

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: *Torch Slabs Mod*

* **Known Fix**: No known fix, but I am sending this to the mod creator.

**Comment by EspieBodespie** [comment]
![fe0c0cd14b1b96ce588ca711a8837c2a](https://user-images.githubusercontent.com/51254988/81960182-68594c00-95c5-11ea-8c9b-a0f701eaba92.png)

**Comment by Sunekaer** [comment]
Thanks EspieBodespie!
