### ISSUE TITLE
Backpacks Loose Inventory Upon Death

### ISSUE THREAD

**Issue by Siveheart** [FTBTeam/FTB-Omnia#77]
* **Modpack Version**: 1.3.0

* **Issue**: Upon death, all your stuff goes into a gravestone like normal. However, if you have a backpack on you with inventory in it when you die, the inventory in the backpack will be gone when you retrieve it from your gravestone. This was not the case before gravestone was updated in this version.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Simply Backpacks, Gravestone

* **Known Fix**: <!-- Unknown

**Comment by Naxanria** [comment]
https://www.curseforge.com/minecraft/mc-mods/gravestone-mod/issues/92

**Comment by Siveheart** [comment]
Thank you.

**Comment by Naxanria** [comment]
https://github.com/Flanks255/simplybackpacks/issues/22 as the GraveStone mod authors says it is not their fault.

**Comment by Naxanria** [comment]
Have not been able to reproduce this issue in Omnia 1.4.0
Therefore closing this issue. If it occurs again feel free to open a new issue for it :)

**Comment by Siveheart** [comment]
Thank you! I appreciate it.
