### ISSUE TITLE
Ratlantis Spawns as a Biome

### ISSUE THREAD

**Issue by Siveheart** [FTBTeam/FTB-Omnia#79]
* **Modpack Version**: 1.3.0

* **Issue**: Ratlantis spawns as a biome within the world instead of as a dimension.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Unknown

* **Mod/s Affected**: Rats

* **Known Fix**: Unknown

**Comment by Sunekaer** [comment]
Hmm, im not able to reproduce this
Could you send me the seed and cords of the biome?

**Comment by Siveheart** [comment]
Sure. The seed is -‭3842966166514925170‬ and the coordinates are 243, 66, 1451

**Comment by Sunekaer** [comment]
Sorry for the delay, i just tested with version 1.4.0 and that seed and those coords and its not a Ratlantis biome for me, could you test with a new world with that seed in 1.4.0 and see if you can reproduce it?
