### ISSUE TITLE
Salt (mekanism) and Salt (xlfoodmod) are not interchangable

### ISSUE THREAD

**Issue by TickTakashi** [FTBTeam/FTB-Omnia#8]
![image](https://user-images.githubusercontent.com/6004230/78647225-2c3e1780-78b2-11ea-92d8-0390cd45e54d.png)

The identically named (and similar looking items) `xlfoodmod:salt` and `mekanism:salt` are not interchangeable despite having the same name and similar appearance. This causes confusion and is unusual/undesirable for high quality modpacks.

If this is the desired behaviour, one of them should either be renamed - perhaps, "table salt" for `xlfoodmod:salt` since it is used in food or "industrial salts" for `mekanism:salt`.

Reproduction steps:

Try making any `xlfoodmod:salt` recipe with `mekanism:salt`. (See image)

**Comment by Naxanria** [comment]
https://github.com/mariot7/XL-Food-Mod/issues/34 Seems it ha snot happened yet. We can add the tags to it, so that will fix this issue
