### ISSUE TITLE
Mods that could be added to Omnia! Check them out! 

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Omnia#82]
Could possibly be a better map to use than the one that is being used right now.
https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap

Some cool mods.
https://www.curseforge.com/minecraft/mc-mods/craft-and-hunt
https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic
https://www.curseforge.com/minecraft/mc-mods/quark

A new dimension for Omnia to discover.
https://www.curseforge.com/minecraft/mc-mods/the-midnight

I would love to see these mods in Omnia and i'm sure a lot of other people would too!

**Comment by kylania** [comment]
I came here to suggest Quark as well, so will just second this request for it. :)  Fantastic QoL mod which I feel would greatly improve this pack.

**Comment by Sunekaer** [comment]
Hi 

Thanks for the suggestions.
Minimap wont be changed.
Quark wont be added, which features from quark is it you looking for?

The rest of them ill have to look into before i can answer on, also i see 2 of the is ARR so i would also need to get permission from the mod dev before we even can use them.

**Comment by CodingJawa** [comment]
Are there any plans to add interdimensional item/fluid transfer?
If not, would it be possible to add some possibility to create obsidian/lava?

Also I think it would be great if there were more possibilities for inventory storage/organisation.

Maybe Ender Storage would be a good mod to add.

**Comment by Sunekaer** [comment]
> Are there any plans to add interdimensional item/fluid transfer?

There already is, mekanism and dimstorage has things to do that 

> If not, would it be possible to add some possibility to create obsidian/lava?

> Also I think it would be great if there were more possibilities for inventory storage/organisation.

Like what?

> Maybe Ender Storage would be a good mod to add.

As i said there's all ready mods doing this
