### ISSUE TITLE
Soul Sand smelts into Soul Glass and Vile Dust-FTB Omnia 1.4.0

### ISSUE THREAD

**Issue by Ratomas** [FTBTeam/FTB-Omnia#83]
Recipe for Soul Glass is smelting of Soul sand and it is the same for Vile Dust. Soul Glass is all you get. The recipe for Soul Glass or Vile Dust needs to be changed to fix this issue.

**Comment by AngelicBeatz** [comment]
Will this be fixed in the next update?

**Comment by Sunekaer** [comment]
This is already fixed, you might be having this issue: https://github.com/FTBTeam/FTB-App/issues/127

try place instance\kubejs\data\modpack\kubejs\recipes.js with this one https://s1.sunekaer.com/t/recipes.js

**Comment by AngelicBeatz** [comment]
hmm that did not seem to work, hmmm for now I have been hand trading players.

http://prntscr.com/spkcy2

**Comment by Sunekaer** [comment]
Do you have it on server and client?

**Comment by AngelicBeatz** [comment]
o I only installed server side, I guess then an update with that new recipes script is the only way it will be put into everyones client since I am just hosting the pack on my server.

**Comment by Lassendc** [comment]
#107 There are en extra line in the server file at 81, removing it will fix the issue

**Comment by AngelicBeatz** [comment]
you mean this? It sure does look out of place but I just wanted to double check.

![image](https://user-images.githubusercontent.com/24941674/83449222-3cd9bc80-a421-11ea-903e-f5e1bfe862f1.png)

**Comment by tjd46** [comment]
> 
> 
> #107 There are en extra line in the server file at 81, removing it will fix the issue

can confirm deleting line 81 fixed this issue for me.
