### ISSUE TITLE
Start.bat file seems to only edit the eula.txt file it creates

### ISSUE THREAD

**Issue by Kraang403** [FTBTeam/FTB-Omnia#84]
* **Modpack Version**: 1.4.0

* **Operating System**: Windows 10

* **Issue**: My friends and I are trying to play Omnia together during the pandemic, and getting fed up with free server providers (since we have limited money) I decided to use one of the spare desktops I have at home as a dedicated server. When trying to install the server i found that the start.bat only creates and edits the eula.txt file before closing. I wasn't able to find any other instances of this happening elsewhere and am not sure what to do. Any and all help will be appreciated.

**Comment by robinofski-dev** [comment]
I had the same problem but running the installer as admin fixed the problem. It didn't put some key lines in the start.bat when not run as admin.
