### ISSUE TITLE
Fps drops when opening inventory.

### ISSUE THREAD

**Issue by markgyoni** [FTBTeam/FTB-Omnia#9]
Modpack: FTB Omnia 1.0.1

Issue: Fps drops everytime to 20-30 from 120 when opening inventory.

**Comment by Naxanria** [comment]
Could you post the logs? Can't do much without :)

**Comment by markgyoni** [comment]
There is no crash just fps drop. I found only the crash logs.

**Comment by Naxanria** [comment]
https://faq.ftb.world/books/ftb-app/page/finding-your-client-logs
Instead of crash logs go to the logs folder and find latest.log

**Comment by markgyoni** [comment]
Thank you! Here is the link: https://paste.feed-the-beast.com/view/3e90bfa3

**Comment by markgyoni** [comment]
And this is off-topic but you can add later the oreexcavation mod to the pack because it has release 1.15.2

**Comment by Sunekaer** [comment]
Hi
Ore Excavation wont be added to the pack, after the authors wishes.
We have added FTB Ultimine instead which does the same thing

**Comment by markgyoni** [comment]
Ok. Thanks.

**Comment by Naxanria** [comment]
Jei seems to cause it. Can you try and type a bunch of random characters in the jei search and see if that helps your fps?

**Comment by markgyoni** [comment]
Yes it helped it goes down to 60-70

**Comment by markgyoni** [comment]
Sometimes it goes back to 30

**Comment by markgyoni** [comment]
I see this ultimine is even cooler (:

**Comment by Naxanria** [comment]
It is because all the items need to be rendered in jei. 
We cant do much about it sadly.

**Comment by markgyoni** [comment]
I hope they fix it later. Thank you!
