### ISSUE TITLE
Sludge Refiner not producing blocks, no recipies.

### ISSUE THREAD

**Issue by rkdragon** [FTBTeam/FTB-Omnia#92]
Modpack Version:  1.4.0

Issue: No recipies for sludge, Sludge Refiner runs and consumes power, but does not consume sludge nor produce blocks, dirt or clay etc.

Link to Log or Crash File Paste: -

Is it Repeatable?: Yes

Mod/s Affected: Industrial Foregoing 1.15.2-2.3.0-6f57752

**Comment by Sunekaer** [comment]
Sludge is a byproduct of the Plant Gatherer
Sludge Refiner needs sludge and power to make dirt and so on work in my dev world
