### ISSUE TITLE
Ever since updating from 1.2 to 1.3 and now in 1.4 it is still an issue of console spamming.

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#93]
* **Modpack Version**: 
started in 1.3.0 after the 1.2.0 update and continues in 1.4.0
* **Issue**: 
22.05 09:38:23 [Server] INFO May 22, 2020 9:38:23 AM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
22.05 09:38:23 [Server] INFO WARNING: Could not lock User prefs.  Unix error code 2.
22.05 09:38:23 [Server] INFO May 22, 2020 9:38:23 AM java.util.prefs.FileSystemPreferences syncWorld
22.05 09:38:23 [Server] INFO WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.

The thing is that it is not affecting the world in any way shape or form from what I see, players are logging in just fine have not lost a thing and the world has not corrupted from what I have seen so I really do not know. I tried googling it to see if there is a fix but I did not find something. I went onto the discord but got no help in the support area so my last place is to post it here.
* **Link to Log or Crash File Paste**: 
this is not a crash this is from the logs, it keeps spamming the console with that
* **Is it Repeatable?**: 
yes on a test server it also started
* **Mod/s Affected**: 
none from what I see
* **Known Fix**:

**Comment by Sunekaer** [comment]
Could you test with a new world?
