### ISSUE TITLE
Requesting Chisel mod or Chisel & Bits

### ISSUE THREAD

**Issue by AngelicBeatz** [FTBTeam/FTB-Omnia#94]
I have seen you guys have installed some decent mods for decoration but that is more furniture. Would we be able to get chisel mod or chisel & bits installed? I believe that would add so much more to the decoration aspect of Omnia and the community's inspired by the pack. This would basically doubling the Decorations or triple them due to the infinite styles of decorations possible added by these mods.

**Comment by Sunekaer** [comment]
These mods are not out for 1.15
