### ISSUE TITLE
Modpack crashes when opening unless newly installed

### ISSUE THREAD

**Issue by Jonahgold90** [FTBTeam/FTB-Omnia#95]
* **Modpack Version**: 
1.4.0

* **Issue**: 

Whenever I open the modpack it crashes after loading for a bit and says "GLFW error 65539: Invalid key 4. Please make sure you have up to date drivers (see aka.ms/mcdriver for instructions)
. This has been happening ever since I got the pack and can only be fixed by uninstalling and reinstalling the pack after I close it every time. ![errorcode](https://user-images.githubusercontent.com/65212176/82713591-0649b800-9c51-11ea-82ce-5572a9c15d0c.PNG)

* **Link to Log or Crash File Paste**: 

It is not in the crash report folder

* **Is it Repeatable?**: 

Yes it happens everytime

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Naxanria** [comment]
There might be a keybind set to a wrong value in your settings. If you delete the settings, it will regenerate on startup and should fix the issue.

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Omnia/issues/57

delete mouse.4 and mouse.5 from options.txt in your instances folder.
