### ISSUE TITLE
Log spam from mekanism + tesseract

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Omnia#97]
* **Modpack Version**: 1.4.0

* **Issue**: Log spam. I talked with mekanism dev, this is tesseract issue. Mekanism only warns about badly implemented inventory handler

* **Link to Log or Crash File Paste**:
![](https://cdn.discordapp.com/attachments/560583846509281280/713814563291660328/unknown.png)

```
[21:11:19] [Server thread/WARN] [Mekanism/]: Tile: com.supermartijn642.tesseract.TesseractTile@4e700bab BlockPos{x=939, y=78, z=428}
[21:11:20] [Server thread/WARN] [Mekanism/]: An inventory's returned content count does not line up with InvStack's prediction.
[21:11:20] [Server thread/WARN] [Mekanism/]: InvStack item: 2 uraninite_ore_poor, ret: 1 air
```

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Mekanism, Tesseract

* **Known Fix**: Up to tesseract mod to fix it

**Comment by AngelicBeatz** [comment]
The log spam I am getting is also from Mekanism but it is spamming this instead with different cords,
24.05 19:24:48 [Server] Server thread/ERROR [MekanismTransmitters/]: Different orphan transmitter was already registered at location! [Coord4D: 1782, 68, -408, dim=DimensionType{minecraft:overworld}]

**Comment by SuperMartijn642** [comment]
@LatvianModder What setup do you use to get this to happen? I can't seem to reproduce it.

**Comment by LatvianModder** [comment]
I tested some more, went to that place etc, and I couldn't reprocude it either for some reason. I guess it was one-time bug. It was just a tesserract with mekanism pipe connected to it to insert items from chest
