### ISSUE TITLE
Dungeon crawl jar crashes

### ISSUE THREAD

**Issue by plumberjim27** [FTBTeam/FTB-Omnia#98]
This mod i believe is causing a crash on my my server, i am very new to this, might be a simple fix.
As soon as i log in i get this error and server crashes. Dungeon crawl jar for craftbukkit was doing the same thing as this mod for omnia. everythings uptodate.

 20:06:13  [Error] Unknown feature id: valhelsia_structures:small_dungeon. 
20:06:14  [Error] Unknown feature id: valhelsia_structures:tower_ruin.
console log doesnt give me much to go off of. 
Would any anti-griefing or world guard affect this mod ? Trying to make a server to host.

**Comment by Naxanria** [comment]
Forge mods on a server with bukkit plugins can cause mayor problems.
For the anti-grieving, the mod pack has FTB Chunks with which they can claim chunks to be protected.

**Comment by Sunekaer** [comment]
Reopen if you can recreate this issue without plugins
