### ISSUE TITLE
RFTools causing crashes

### ISSUE THREAD

**Issue by h3ctic-ritchie** [FTBTeam/FTB-Omnia#99]
* **Modpack Version**: 1.4.0

* **Issue**: Trying to use RFTools is causing the game to crash

* **Link to Log or Crash File Paste**: attached

* **Is it Repeatable?**: yes every time

* **Mod/s Affected**: RFTOOLS

* **Known Fix**: unknown
[crash-2020-05-24_20.49.41-client.txt](https://github.com/FTBTeam/FTB-Omnia/files/4673542/crash-2020-05-24_20.49.41-client.txt)

**Comment by Sunekaer** [comment]
please use https://paste.feed-the-beast.com/ for the log file
